### ISSUE TITLE
How to run "particle_filter.py"

### ISSUE THREAD

**Issue by gibson24** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#105]
Hi
I tried to run "particle_filter.py", but occurs error.
Please teach me how to run "particle_filter.py".

**Comment by gibson24** [comment]
I add import sentence to "particle_filter.py" but occurs error.
The error sentence is "TypeError: There is no Line2D property "weights""
Please teach me how to run "particle_filter.py".

**Comment by rlabbe** [comment]
Sorry, this is utterly obsolete. Your best bet is to just read chapter 12.

Somehow I deleted the ParticleFilter class from this file. If you go back to the version in check in a0b7a50b05bd60858a1564b317af19cc6602505c you will find the class. I have no idea if that version of the file runs either. 

However, I will be deleting this file from the repository going forward. It is just some code I wrote while I was working on the particle filter chapter and is not a part of the book.
