### ISSUE TITLE
Issue with interactive_gh graph in 01-g-h-filter.ipynb.

### ISSUE THREAD

**Issue by neonquill** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#112]
When I first load the notebook and run all cells, the interactive graph looks fine.  When I change a value by moving a slider (in particular g), the zs values change to very large values.  This can be fixed by re-running the individual cell before interacting with the graph.

I suspect that the zs array is getting updated below (in the train example), so when I change a value, the plot refreshes to show the data from a different example.  I'm happy to submit a pull request, but not quite sure if it makes more sense to rename the array or to just add a note warning of this issue.

### Example:

First load:
![initial](https://cloud.githubusercontent.com/assets/845294/18023964/6175ba92-6bce-11e6-8beb-fcc3b69e910d.png)

After changing the `g` value to the minimum:
![after_changing_g](https://cloud.githubusercontent.com/assets/845294/18023965/6c078fd0-6bce-11e6-8fcd-93e9ada433bb.png)

If I re-evaluate just that cell and then change `g` everything looks fine:
![after_reload_and_change_g](https://cloud.githubusercontent.com/assets/845294/18023967/72b2d83a-6bce-11e6-9a36-527e9c5f3009.png)

**Comment by neonquill** [comment]
Thinking about this more, I realize that there's a caveat about the general issue at the beginning of this file, it just took me a long time to connect this behavior with that warning.  I'm going to leave this open just in case anybody else feels like a special warning is warranted here.

**Comment by rlabbe** [comment]
I think this is a valid complaint. The book used to be far less interactive, so reusing variable names was easy. But easy is the enemy of good. I will fix this so you can run the cells in a more arbitrary order.

**Comment by rlabbe** [comment]
Okay, I've checked in a fix for this chapter. The problem may still occur in other chapters.
