### ISSUE TITLE
Typo in 06-Multivariate-Kalman-Filters.ipynb?

### ISSUE THREAD

**Issue by fjp** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#115]
In chapter/file 06-Multivariate-Kalman-Filters.ipynb you wrote 

> On the other hand, it is trivial to convert a state containing position and measurement into a equivalent "measurement" containing only position.

But I think instead of 

> containing position and measurement

you meant 

> containing position and velocity

**Comment by rlabbe** [comment]
Correct! I've checked in a fix.
