### ISSUE TITLE
Broken URL in notebook 05 Multivariate Gaussians

### ISSUE THREAD

**Issue by esvhd** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#117]
Hi Roger,

Noticed that the link http://git.io/vmv6e in notebook 05 Multivariate Gaussians is broken. It's referenced just after the Engine Temperature vs Lifespan chart. You should be able to find it just by searching as well.

Not critical but would be great to have the correct one.

Thanks.

Will

**Comment by rlabbe** [comment]
Fixed. Thanks!
