### ISSUE TITLE
Errors in 06-Multivariate-Kalman-Filters

### ISSUE THREAD

**Issue by ryanmeasel** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#122]
**Line 2233:**

> "...velocity is updated by the error in the position times _the a_ value..."

**Line 2621:**

> "Why are the ellipses for  R=5^2  shorter, and more tilted than the ellipses for  R=0.5^2."

The comma is incorrect, and it should end in a question mark. Additionally, "shorter" is wrong in all respects (x-axis, y-axis, eigenvalues), and "more titled" is not well defined.

**Code Listings in "Smoothing the Results":**

The batch filter output is calculated as "Xs", but the plots use "xs" which is actually the output from filter in the "Batch Processing" section.

**Comment by rlabbe** [comment]
Thanks, I've fixed and pushed this.
