### ISSUE TITLE
Reading Chapter 04 in Browser gives an error

### ISSUE THREAD

**Issue by stefannnnnn** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#127]
When opening Chapter 04 directly through gituhub in the browser (not via binder), github is not able to display it.

All other chapters work.

**Comment by rlabbe** [comment]
I had this problem earlier as well. Jupyter team says it is a Github problem. It renders fine in nbviewer, by the way, if you are trying to read it online. I've issued a support request to GitHub to see if we can't resolve the problem.

**Comment by cemysf** [comment]
you can view it from here until github fixes the problem
http://nbviewer.jupyter.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python

**Comment by rlabbe** [comment]
Bit the bullet, deleted one paragraph at a time, and figured out the problem. I had

```Python
update(x, P, z, R)
```

in a cell. Python should not be capitalized. Odd that everything else rendered it fine, but not GitHub, but it is fixed and working now.
