### ISSUE TITLE
Improve demonstration of dynamic error in 01-g-h-filter.ipynb

### ISSUE THREAD

**Issue by eggonabull** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#131]
After ```predict_using_gain_guess(initial_guess, -1, do_print=False)``` you switch back to using +1 as your gain_rate guess. I think the demonstration would be both more effective and more fair starting the following formula and next example with a gain of -1.  

If you reject that suggestion, I'd suggest you at least explicitly state that you're going back to using a gain of 1.  It made me think I'd missed a sign somewhere in my reading of the previous formals and seeing (160+1) in that formula.

**Comment by rlabbe** [comment]
I agree - I've pushed the change. Thanks.
