### ISSUE TITLE
Correct misrepresentation of symbols in pdf book TeX equations?

### ISSUE THREAD

**Issue by MatthiasErdmann** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#137]
Having managed to create the pdf, I find that TeX equations - at least in the pdf that I was able to create after installing a full TeX distribution - repeatedly contain misrepresented symbols:
- the first occurs on p. 63: "scale=...=prob_correct/(1*prob_correct)" - the multiplication sign should be a minus sign
- on p. 68, instead of a multiplication sign, a headlong exclamation mark is shown, then a some lines below a "sun" symbol
- on p. 71, the convolution is defined with the headlong exclamation mark instead of a multiplication sign, and what should be a minus sign in the argument is shown as a multiplication sign
etc.
I hope this is not an error in my TeX installation. 
By the way: Thanks for your invaluable book and filterPy library.

**Comment by rlabbe** [comment]
Has anyone else seen this? I'll close soon if not. This seems like a TeX installation issue to me.

**Comment by MatthiasErdmann** [comment]
Thank you for commenting. I am not sure, since had a fresh TeXlive (full, otherwise it did not work) installation. Currently I am happy with the pdf version of January 14 you provided on Google drive, thanks a lot. I found creating the pdf astonishingly painful, so I will be happy to do without, however not without your book. (Did I say I find it invaluable? So far following your Adaptive Filtering hints proved to be successful.)
