### ISSUE TITLE
Bug in data generation function: compute_dog_data()

### ISSUE THREAD

**Issue by asmwarrior** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#139]
In file 06-Multivariate-Kalman-Filters.ipynb, when generate the dog tracking data.
```
def compute_dog_data(z_var, process_var, count=1, dt=1.):
    "returns track, measurements 1D ndarrays"
    x, vel = 0., 1.
    z_std = math.sqrt(z_var) 
    p_std = math.sqrt(process_var)
    xs, zs = [], []
    for _ in range(count):
        v = vel + (randn() * p_std * dt)
        x += v*dt
        xs.append(x)
        zs.append(x + randn() * z_std)
    return np.array(xs), np.array(zs)
```

I think there is a bug in the line `v = vel + (randn() * p_std * dt)`, it should be  `v = vel + (randn() * p_std)`, because the `dt` is not needed here. So, I think this is a bug, what do you think?

The lucky thing is that currently, `dt` is set to `1.0`, so that you can't see the bug, right? Thanks.

**Comment by rlabbe** [comment]
Fixed, thanks!
