### ISSUE TITLE
Mixed-up "product" and "sum"

### ISSUE THREAD

**Issue by jrussino** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#140]
In chapter 03-Gaussians, section "Computational Properties of Gaussians", you state the following:
"the product of two independent Gaussians is another Gaussian! The sum is not Gaussian, but proportional to a Gaussian."
and shortly thereafter:
"the result of multiplying two Gaussians is yet another Gaussian."

However you then go on to state (and demonstrate, and use extensively in later chapters) that in fact the **sum of two Gaussians is a Gaussian**, and the **product of two Gaussians is proportional to a Gaussian**.

(i.e. these two cases appear to be mixed up in the introductory paragraphs).

**Comment by cdhuanghl** [comment]
I also have found this problem!

**Comment by rlabbe** [comment]
Fixed and pushed. Thanks!
