### ISSUE TITLE
Missing power of two in 03 - Gaussians notebook

### ISSUE THREAD

**Issue by npp1993** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#145]
I believe there is a missing power of two in the section "Sum of Gaussians" in the 03 - Gaussians notebook.  In the first step of performing the convolution in which the PDFs for the Gaussians are substituted, the terms (x - z - u_z) and (x - u_p) should be squared, but they are not.

**Comment by rlabbe** [comment]
Fixed, thanks!
