### ISSUE TITLE
Resampling is incorrect in chapter 12

### ISSUE THREAD

**Issue by cntaylor** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#146]
Thank you for your tutorial as people I have been trying to explain the particle filter to are using your code and finding it very useful.  That said, there is one error that I noticed that is repeated multiple times in chapter 12.  When you are resampling, you use the code:

    # resample according to indexes
    particles[:] = particles[indexes]
    weights[:] = weights[indexes]
    weights /= np.sum(weights) # normalize

Note, however, that because higher-weighted particles have already been selected, they are no longer higher weight.  The resampling should really be:

    # resample according to indexes
    particles[:] = particles[indexes]
    weights[:] = 1/N

Thanks!

**Comment by rlabbe** [comment]
Fixed. Thanks so much!
