### ISSUE TITLE
Question: 11-Extended-Kalman-Filters.ipynb - "Solving each in turn dh/dxdot = 0 - how did you get this?"

### ISSUE THREAD

**Issue by MontyTHall** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#151]
Not a bug but more of a question.  I'm dying to know how you got dh/dxdot = 0 located @ "Solving each in turn".  Specifically d sqrt(x ** 2 + y ** 2) / dxdot = 0.  To me x and y are functions of time and via chain rule:

dh/dxdot = dh/dx dx/dxdot = x/sqrt(x ** 2 + y ** 2) dx/xddot.  
Where dx/dxdot = (dx/dt)/(dxdot/dt) = velocity/acceleration.  

So we have  x/sqrt(x**2 + y **2) vx / ax <- this isn't zero.  If x(t) = t and y(t) = t, ax = 0, so I get infinity.   If you can get me sorted out on this, would greatly appreciate it.

**Comment by MontyTHall** [comment]
Nvm.  It's a partial derivative.  It's been ages since I did calc.  when x & y are fixed, h is basically constant.  Thanks.  Sorry to bother you.

**Comment by rlabbe** [comment]
No problem.
