### ISSUE TITLE
03-Gaussians: the deducing of VAR(X) is not correct

### ISSUE THREAD

**Issue by chirping78** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#154]
The arithmetic calculation of VAR(X) is correct, since you are actually calculating "Sample variance". See https://en.wikipedia.org/wiki/Variance for the "Sample variance" definition and how it is deduced. 
 
More accurately, you are calculating "maximum likelihood estimate of the variance" here. Cited from the numpy.var() help doc:
 
```
In standard statistical practice, ``ddof=1`` provides an
    unbiased estimator of the variance of a hypothetical infinite population.
    ``ddof=0`` provides a maximum likelihood estimate of the variance for
    normally distributed variables.
```
 
Based on above understanding, your these words are inconsistent, and so the deducing of VAR(X) equation is not correct: first you said the heights are "uniform distributed", then they are "normal distributed"?
```
we will assume that any height is equally probable, so we can substitute that into the equation above to get VAR(X)=
```
```
For now I'll say that for many things 68% of all values lie within one standard deviation of the mean.
```

**Comment by rlabbe** [comment]
Fixed.
