### ISSUE TITLE
Error in 04-One-Dimensional-Kalman-Filters?

### ISSUE THREAD

**Issue by bale0611** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#160]
for z in zs:
    # predict
    dx = velocity*dt
    pos = pos + dx
    var = var + sensor_var

    # update
    pos  = (var*z + process_var*pos) / (var + process_var)
    var = (var * process_var) / (var + process_var)
Maybe switch "sensor_var" and "process_var"?

**Comment by rlabbe** [comment]
Yup, fixed!
