### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'kappa'

### ISSUE THREAD

**Issue by gereziherw** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#167]
When I try to execute ukf_range.py I have got this error, I thought the error occur because kappa is not mentioned in the init method of the UKF and I the following changes to 
f = UKF(3, 1, dt= dt, hx=hx, fx=fx, kappa=1) as follows,
points = 1
f = UKF(3, 1, dt= dt, hx=hx, fx=fx, points=points)
then another error occur, 
AttributeError: 'int' object has no attribute 'num_sigmas'
and I stopped going further. could you please help me in this regard? 
Thank you.

**Comment by rlabbe** [comment]
points needs to be a class.  As the docstring in the __init__ function states:

    Class which computes the sigma points and weights for a UKF
    algorithm. You can vary the UKF implementation by changing this
    class. For example, MerweScaledSigmaPoints implements the alpha,
    beta, kappa parameterization of Van der Merwe, and
    JulierSigmaPoints implements Julier's original kappa
    parameterization. See either of those for the required
    signature of this class if you want to implement your own.

I'm guessing you might have been looking at the examples directory? Unfortunately that directory is quite out of date.

The best documentation is my book, chapter 10:
https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python

I know the documentation of this library is underwhelming, but life is limited. Sorry

**Comment by gereziherw** [comment]
Thank you Very much Rlabbe, I will do as your suggestion. You are really life saver especially for  all  students who are financially struggling like me, who can't get access to the most costly  books required to learn Kalman filtering. Much Respect.
