### ISSUE TITLE
[02-Discrete-Bayes] 

### ISSUE THREAD

**Issue by ycchangtw** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#170]
In the paragraph  "Adding Uncertainty to the Prediction"
The book states"
perfect_sensor() assumes perfect measurements, but all sensors have noise. What if the sensor reported that our dog moved one space, but he actually moved two spaces, or zero? This may sound like an insurmountable problem, but let's model it and see what happens."

Should the sensors have noise should be replaced with "system process error". In the process model , the dog want to move, and the process error refers to the dog moves  one space, but actually move more than one space due to certain reasons (For example, the microwave in the kitchen turns on, and he goes streaking off)

**Comment by rlabbe** [comment]
No, this is talking about the sensor making an error. The dog is at 37 (say), but the sensor detected 36. That's entirely different from the process error - we may be predicting the dog is at 39. In this case the sensor error is -1, and the process error is +2.
