### ISSUE TITLE
Can i translate this into Chinese?

### ISSUE THREAD

**Issue by deyuhua** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#172]
In order to many Chinese developer can access this awesome resource , can i translate it into Chinese version?

**Comment by deyuhua** [comment]
@rlabbe

**Comment by rlabbe** [comment]
Sure. You just need to follow the conditions of the license:

https://creativecommons.org/licenses/by/4.0/

Basically, attribute the original to me, and don't restrict other's writes to do the same.
