### ISSUE TITLE
Question on the library gh_internal

### ISSUE THREAD

**Issue by Rashid-S** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#174]
I'm trying to run an example from your book on page 17. I write code to Jupiter in a web browser. But I get an error: "No module named 'gh_internal' ". Help me to understand. The filterpai library is installed like.
http://prntscr.com/glrr5r

**Comment by rlabbe** [comment]
gh_internal is part of the book, not FilterPy. It is in the kf_book subdirectory. Either your notebook has to be in the same directory, or you need to add the kf_book subdirectory to your pythonpath so the `import` can find it.
