### ISSUE TITLE
ValueError: could not broadcast input array from shape (2,1) into shape (2) in UKF

### ISSUE THREAD

**Issue by oikonang** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#176]
Hello Roger,

First of all congrats for this great book! It would have taken me ages to build something even that simple as what you will see later without your help. 

 I am building my dissertation on estimating ship's speed through water using Doppler velocity measurement and some manually calculated velocities. So non-linear sensor fusion approach is what I am looking for.

I used the 2D sensor fusion linear approach from the train example on chapter 8 and it worked fine. I replaced 2D position from the example with 2 different velocities and I added acceleration as an unknown factor. I am not sure if the approach is the right one but the resulting velocity is quite good with some tuning.

Now I am trying to replicate the same problem, using **UKF** and I get this

```
ValueError: could not broadcast input array from shape (2,1) into shape (2) in UKF
```

My code is the following:

### Step 1: Implement **f** and **h** functions
```python
def f_(x, dt):
    """ state transition function"""
    F = np.array([[1, dt],
                  [0,  1]])
    return np.dot(F, x)

def h_(x):
    """ measurement function"""
    H = np.array([[1,0],
                [1,0]])
    
    return np.dot(H, x) 
```

### Step 2: Design the filter
```python
from filterpy.kalman import MerweScaledSigmaPoints
from filterpy.kalman import UnscentedKalmanFilter as UKF
from filterpy.common import Q_discrete_white_noise

dt = 1. # time step 1 second

# Define sigmas and initialize UKF
sigmas = MerweScaledSigmaPoints(2, alpha=.1, beta=2., kappa=1.)
ukf = UKF(dim_x=2, dim_z=2, fx=f_, hx=h_, dt=dt, points=sigmas)

# Define measurement noise matrix
ukf.R = np.diag([9, 9]) # 3 knots

# Define the process noise matrix
ukf.Q = Q_discrete_white_noise(dim=2, dt=dt, var=0.01)

# Define state variable and the covariance matrix
ukf.x = np.array([[0, 0]]).T
ukf.P = np.eye(2) * 500.
```

### Step 3: Collect the measurements from dataframe
```python
## Transpose because the input is a 2D vector
zs = np.array([np.array([[Kalman_df['STW_log'][i],Kalman_df['STW_calc'][i]]]).T for i in range(len(Kalman_df))])
```

### Step 4: Run the UKF
```python
xs, covs = ukf.batch_filter(zs)
```

After I run the last step I get the value error indicating the sigma points
```
/usr/local/lib/python2.7/site-packages/filterpy/kalman/sigma_points.pyc in sigma_points(self, x, P)
    142 
    143         sigmas = np.zeros((2*n+1, n))
--> 144         sigmas[0] = x
    145         for k in range(n):
    146             sigmas[k+1]   = self.subtract(x, -U[k])

```

Any help would be appreciated. 

Thank you!

**Comment by rlabbe** [comment]
It is a little hard to say, but I suspect zs is malformed. The exception is saying the shape of `sigmas[0]` is different from the shape of `x`. Put a breakpoint there and inspect what you have. I suspect you will find that `sigmas[0] looks like [[1.2343], [2.34333]] and x looks like [2.2343, 4.34433] (wrong dimension).

I'm a bit confused because the assignment to zs includes the subscript i, but it is not shown as being in a loop. In any case your best bet is just set a breakpoint, figure out what the dimension are, and what they should be.

**Comment by rlabbe** [comment]
It is a little hard to say, but I suspect zs is malformed. The exception is
saying the shape of `sigmas[0]` is different from the shape of `x`. Put a
breakpoint there and inspect what you have. I suspect you will find that
`sigmas[0] looks like [[1.2343], [2.34333]] and x looks like [2.2343,
4.34433] (wrong dimension).

I'm a bit confused because the assignment to zs includes the subscript i,
but it is not shown as being in a loop. In any case your best bet is just
set a breakpoint, figure out what the dimension are, and what they should
be.

**Comment by oikonang** [comment]
Thank you for the quick response!

I have tried with many variations of **zs**.

The above code with the subscript i you mentioned, gives me this:
```
zs shape:  (1509904, 2, 1)
First 3 values of zs: 

[[[-0.2       ]
  [ 0.00027363]]

 [[-0.2       ]
  [ 0.00027363]]

 [[-0.2       ]
  [ 0.00027363]]]
```

**Comment by rlabbe** [comment]
Looking a little further I'm confused. F implies that x contains [x, x']. But then it looks like z contains 2 velocities. h_ takes the first element of x, so h([[3.1], [4.5]) == [[3.1], [3.1]], and you can't compare positions to velocities. if x actually contains 2 velocities, then I don't see how your design of F is correct.

I can't solve your problem for you, but I unless misunderstand something I'm not sure the design is correct.

**Comment by rlabbe** [comment]
Wait, I see the problem. This is probably an unfortunate design decision, but the UKF code expects x to be a single dimension array: x = np.array([0., 0.])

FWIW I found this by copy/pasting your code and setting a breakpoint. x = [[0.], [0.]], and sigmas[0] = array([0., 0]) at which point I went "ohhh..... of course".

**Comment by oikonang** [comment]
The approach that I am following is similar to the one at the chapter 8 at the sensor fusion section. So I suppose that z is a 2D with two velocities and and state **x** contains velocity *\dot x* and unknown acceletation *\doubledot x*.

Which brings the following H:
$$ \begin{bmatrix}STW_{log} \\ STW_{calc}\end{bmatrix} = \begin{bmatrix}1 &0 \\ 1& 0\end{bmatrix} \begin{bmatrix}\dot x \\ \ddot x\end{bmatrix}$$

Do you think I approach it correctly?

Thank you for your time.

**Comment by oikonang** [comment]
Sorry. This is the correct Latex code
```
$$
\begin{bmatrix}STW\_log \\ STW\_calc \end{bmatrix} = \begin{bmatrix}1&  0\\1 &  0\end{bmatrix}\begin{bmatrix}\dot x \\ \ddot x \end{bmatrix}$$
```
I dont know how to render latex on github..

**Comment by oikonang** [comment]
I made it work! 

As you said, I replaced state **x** with:
```python
ukf.x = np.array([0, 0])
```
and the **zs** so as to bring 
```
zs shape:  (1509904, 2)
First 3 values of zs: 

[[-0.2         0.00027363]
 [-0.2         0.00027363]
 [-0.2         0.00027363]]
```

It takes double the time to run compared to the linear version thought and the results are almost the same. Next step it to smooth the results.

Thank you very much for the help Roger!

Btrgs,
Angelos
