### ISSUE TITLE
inconsistent license

### ISSUE THREAD

**Issue by eshellman** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#18]
The license on the readme (updated  Mar 9, 2015) is CC BY, but the license called out in license.html (May 16, 2014) is CC BY-NC-SA. Legally, the BY takes precedence over the BY-NC-SA and is irrevocable, but they should be the same to avoid confusion.

**Comment by rlabbe** [comment]
My intention was CC BY, I think I just didn't update the html file to reflect that. I'm not terribly knowledgeable about CC, I just know I want minimal restrictions other than acknowledgement.

**Comment by rlabbe** [comment]
Fixed.

**Comment by eshellman** [comment]
CC BY does the trick. I generally recommend specifying an attribution URL as the 4.0 licenses give weight to that, but I see you've done that already with the CC license chooser. Excellent!
