### ISSUE TITLE
Error in g-h chapter

### ISSUE THREAD

**Issue by vinaybk** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#185]
Hi rlabbe,
     I am trying to read the book along with python code executions. I am using jupyter notebook of python version 3.0. I am getting following errors.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-26d5dd208d25> in <module>()
      2 get_ipython().magic('matplotlib inline')
      3 from __future__ import division, print_function
----> 4 from book_format import load_style
      5 load_style()

C:\Users\admin\Kalman-and-Bayesian-Filters-in-Python\book_format.py in <module>()
     54 # called when this module is imported at the top of each book
     55 # chapter so the reader can see that they need to update FilterPy.
---> 56 test_filterpy_version()
     57 
     58 pylab.rcParams['figure.max_open_warning'] = 50

C:\Users\admin\Kalman-and-Bayesian-Filters-in-Python\book_format.py in test_filterpy_version()
     39 def test_filterpy_version():
     40 
---> 41     import filterpy
     42     from distutils.version import LooseVersion
     43 

ModuleNotFoundError: No module named 'filterpy'

**Comment by Zepy1** [comment]
Hi vinaybk, 
> ModuleNotFoundError: No module named 'filterpy'

Did you install the filterpy library?

**Comment by vinaybk** [comment]
Yes, I installed filterpy.

**Comment by vinaybk** [comment]
Still having issues.

**Comment by vinaybk** [comment]
Any luck rlabbe?

**Comment by rlabbe** [comment]
I cannot debug your setup. The error states that it cannot import filterpy, so it is not installed, or installed in a different python than the one running the notebook. I don't think it has anything to do with my book.

**Comment by vinaybk** [comment]
I think you are right, i was using python3 and installation happened in 2.7.
So right at beginning of your book i put the following:
!pip install filterpy
    This helped me to solve the issue. May be you can put this as part of your book to solve this issue. I am sure many would be having this kind of problem.

**Comment by Xiaohong-Deng** [comment]
I'm using the alternative way to use the book, which is set up a conda env as instructed `conda env update -f environment.yml`.

and I encountered 

> No module named 'filterpy'

I tried different IDEs including atom+ hydrogen, which is able to fetch a package from whichever env folder it lies in. I tried `!pip install filter` when I was running notebook in the browser in kf_bf env. showed me exactly the same message I saw in terminal.

> Requirement already satisfied: filterpy in c:\coding\anaconda3\envs\kf_bf\lib\site-packages
> Requirement already satisfied: matplotlib in c:\coding\anaconda3\envs\kf_bf\lib\site-packages (from filterpy)
> Requirement already satisfied: scipy in c:\coding\anaconda3\envs\kf_bf\lib\site-packages (from filterpy)
> Requirement already satisfied: numpy in c:\coding\anaconda3\envs\kf_bf\lib\site-packages (from filterpy)
> Requirement already satisfied: six>=1.10 in c:\coding\anaconda3\envs\kf_bf\lib\site-packages (from matplotlib->filterpy)
> Requirement already satisfied: python-dateutil>=2.1 in c:\coding\anaconda3\envs\kf_bf\lib\site-packages (from matplotlib->filterpy)
> Requirement already satisfied: pytz in c:\coding\anaconda3\envs\kf_bf\lib\site-packages (from matplotlib->filterpy)
> Requirement already satisfied: cycler>=0.10 in c:\coding\anaconda3\envs\kf_bf\lib\site-packages (from matplotlib->filterpy)
> Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\coding\anaconda3\envs\kf_bf\lib\site-packages (from matplotlib->filterpy)

Now I'm wondering if it's because I'm on windows?

**Comment by Xiaohong-Deng** [comment]
Seems it works fine with root environment of anaconda3. Use anaconda prompt to pip install filterpy.
