### ISSUE TITLE
how to provide typo fixes?

### ISSUE THREAD

**Issue by ernstklrb** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#186]
Hello @rlabbe 

while reading, I fix smaller typos. I do this in a fork.

How would you like to receive the pull request? All fixes in one commit? One commit per fix? One commit per ipynb File?

E.

**Comment by rlabbe** [comment]
One per file is usually fine. Occasionally I'll reject a commit and then make the fixes myself if the python runs of cells are not identical to mine. Notebooks don't 'play' so well with git sometimes due to the mix of source and executed results.
