### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by gusutabopb** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#192]
In [02 - Discrete-Bayes](https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/02-Discrete-Bayes.ipynb), it seems the link to the NumPy intro video by Jake Vanderplas is broken: https://vimeo.com/79820956.

In [07 - Kalman Filter Math](https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/07-Kalman-Filter-Math.ipynb), the link to *Computational Physics in Python* is also broken: http://phys.csuchico.edu/ayars/312/Handouts/comp-phys-python.pdf

**Comment by rlabbe** [comment]
Both of those have seemed to been removed from the internet by the owners. I've deleted the links, from the book.
