### ISSUE TITLE
Incorrect Symbols Rendered in PDF

### ISSUE THREAD

**Issue by harout** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#193]
It looks like what should be a "-" is rendered as "*" in the PDF (chapter 5). This does not occur in an older version of the PDF.

![cov](https://user-images.githubusercontent.com/1213786/33653814-0b2bb988-da23-11e7-8116-91be91b37f98.jpeg)

**Comment by rlabbe** [comment]
I really don't know what to do about this. It also seems to be displaying \vdots and \hdots as deltas for some reason. It could be my LaTeX installation is broken, there is something wrong with the nbconvert pdf exporter, or ???

**Comment by rlabbe** [comment]
Ah, figured it out. I started using the stix font, and for whatever reason it was messing up some of the math symbols. Reverted to the default font, and everything is fine. A new PDF is uploaded now.
