### ISSUE TITLE
Chrome is not loading any notebooks

### ISSUE THREAD

**Issue by aitatanit** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#20]
I'm using the latest version of Anaconda (still python 2.7) along with Chrome under Ubuntu but I am not able to load any of the pages when I click on the notebooks. I get an error message "Bad request". Any ideas on how to get around this?

**Comment by rlabbe** [comment]
Note the version of IPython has nothing to do with the Python version.
IPython 3.0 can run Python 2.7, 3.4, or whatever. It's confusing. IPython
3.0 with Python 2.7 should be fine.

**Comment by aitatanit** [comment]
I tried anaconda 3.4 & 2.7 on Windows and Linux. I get the following errors as shown in the pic below. 

![capture](https://cloud.githubusercontent.com/assets/2544445/6763366/161244b4-cf47-11e4-8b30-87a93e33a69b.PNG)

**Comment by rlabbe** [comment]
You need to be running IPython 3.0. This has nothing to do with the version of Python (3.4 or 2.7). Can you confirm that you are running IPython 3.0? (just run it from the command line, paste what it says).

**Comment by aitatanit** [comment]
All right, I got it now. I assumed that ipython 3 was in anaconda 3. It's working now. Thanks
