### ISSUE TITLE
Replace scipy.linalg.cholesky(a) to np.linalg.cholesky(a)

### ISSUE THREAD

**Issue by striatum** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#200]
My environment is:

>           conda version : 4.4.6
>     conda-build version : 3.0.27
>          python version : 3.6.4.final.0
>                platform : osx-64
>              user-agent : conda/4.4.6 requests/2.18.4 CPython/3.6.4 Darwin/17.3.0 OSX/10.13.2
>                 UID:GID : 502:20

Cell containing following line:

    scipy.linalg.cholesky(a)

produces an error, but if I replace it with

    # assuming: import numpy as np
    np.linalg.cholesky(a)

all works fine.

(Great book! Many thanks! 😊)

**Comment by rlabbe** [comment]
I don't know what cell you are referring to, nor what "error" occurs. An exception? If so, what is the exception? And what is the value of a?

Are you talking about the cell in chapter 10 that reads
import scipy
a = np.array([[2., .1], [.1, 3]])
s = scipy.linalg.cholesky(a)
np.dot(s, s.T)

**Comment by striatum** [comment]
Yes, sorry I forgot to add that specs.

**Comment by rlabbe** [comment]
Closing given lack of follow up, and because scipy's cholesky function is very robust, and I won't replace it without a very sound reason.
