### ISSUE TITLE
No file "book.tex"

### ISSUE THREAD

**Issue by DapangLiu** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#202]
Hi, I tried to build the book but it said the book.tex file is missing. Any ideas?

**Comment by rlabbe** [comment]
I would need a lot more info to guess. But, the scripts for unix are way out of date, I am doing this on Windows these days.

On Windows, you navigate to the pdf directory and run build_book.

README is out of date - it says the windows files are out of date, but it is the unix files that are out of date.
