### ISSUE TITLE
Suggestion for Readability: Use namedtuple

### ISSUE THREAD

**Issue by spradlig** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#206]
I am re-learning Kalman filters using my Masters thesis from 2004 and your book. I am currently reading the 1D Kalman filter chapter (04). I have come to the portion:

```
def predict(pos, movement):
    return (pos[0] + movement[0], pos[1] + movement[1])
```

It didn't take but a second to figure this out but it would be much more explicit had the pos and movement tuples been namedtuples. Like this:

```
from collections import namedtuple

gaussian = namedtuple(
    'Gaussian',
    [
        'mean',
        'variance'
    ]
)

pos = gaussian(mean=10, variance=0.2**2)
```

The variable pos is now (mostly) immutable. You could also use SimpleNamespace or recordtype if you wanted something mutable. I'm just now discovering SimpleNameSpace but coming from a MATLAB background I like it as a potential replacement for the struct variable type I used to use all the time in MATLAB.

Define movement the same way as pos.. Then:

```
movement = gaussian(mean=15, variance=0.7**2)

def predict(pos, movement):
    return gaussian(
        mean=pos.mean + movement.mean, 
        variance=pos.variance + movement.variance
    )
```

No, it isn't that hard to figure out. Yes, your version is significantly fewer lines of code. But clearly what this version of the code is doing is much more obvious.

**Comment by rlabbe** [comment]
I like this suggestion; I actually had it coded this way a long time ago (maybe before the first commit to GitHub). I recall having a bit of difficulty getting it to cooperate with some of the library functions, but I also think I was trying to strew this usage throughout FilterPy. I think just making it part of this chapter but not part of FilterPy is a good idea.

**Comment by spradlig** [comment]
I love the book so far and appreciate the effort. I suspect that implementing this throughout your filterpy code would take a lot of work. 

Just in case you haven't explored the namedtuple thoroughly... When using a namedtuple you can use an index, i.e. 0, or the name, i.e. mean. So in the example above, pos[0] == pos.mean at least for Python 3.6.

I haven't yet gone through the filterpy code so I'm not sure how much this would help with regards to the libraries. Nor am I suggesting you need to rewrite the library. IMO, stable and functional is more important than anything else. Your code is pretty easy to read so I suspect that with the book I can figure out what the code in filterpy is doing. If I can't figure it out, then I don't really know what I'm doing and need to reread the book.

Thanks for the effort on this. It's way too easy to get lost in the math on this stuff and I appreciate the simple examples for the purpose of building intuition. I'm being reminded of all sorts of things I used to know off the top of my head.

**Comment by rlabbe** [comment]
I pushed a change that incorporates this. Let me know what you think.

https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/04-One-Dimensional-Kalman-Filters.ipynb

**Comment by spradlig** [comment]
As expected, the flow of the code and text isn't as smooth as before.
However, I find the changes to be more readable and explicit. Much easier
to link the math to the code. Which, IMO, allows for a faster assimilation
of the math (and it's implementation) without getting hung up in the code
if you aren't already familiar with the math and Python at the time you are
reading the chapter.


ᐧ

**Comment by rlabbe** [comment]
I updated the text description a bit to make it a bit more concise. I will not be propagating this into the rest of the book - the multidimensional filters use state variables and separate covariance matrices so this notation is not useful. I think I addressed your comment, and am closing the issue. Please reopen or raise a new issue if necessary.

**Comment by spradlig** [comment]
Sorry, I should have closed this. I agree, you clearly addressed my suggestion. Thank you.
