### ISSUE TITLE
Math issues

### ISSUE THREAD

**Issue by spradlig** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#208]
There have been multiple places in the book where the mathcal script for the math is visible instead of the equations.

Additionally, as I go through the book I've noticed a number of places where you present row vectors when they should be column vectors. (I'm not talking of the row vectors you create with the intent of transposing them later.)

In the image below it looks like you have 2 equations that have run together into a single line. The row vector at the end of the 1st equation should be a column vector not a row vector.

![math](https://user-images.githubusercontent.com/3074852/35592014-f9ab997c-05c8-11e8-9d5a-b35d9b40d8cd.png)

(In case the image doesn't show, the image is of the equation just above **In [12]** of **Designing the Process Model** of **Ch 06**.)

I'll provide a list of items as I find them - if you want them. If you don't want them then I'll keep my mouth shut.

**Comment by rlabbe** [comment]
What source are you using? the PDF, a local notebook, a notebook on binder, the GitHub viewer, etc.

I can't do anything about the GitHub viewer, and it has known rendering issues. Same for nbviewer.

If it is happening in the notebook itself, then it is almost certainly my failure.

If in the PDF, that's up to the exporter code. We may be able to generate a bug against it.

I'm interested in hearing about at least some of them if it is happening in a notebook. Tell me about 1 if in the other places, but not a notebook.

Also, sometimes Mathjax fails in the browser. You can shut the notebook down, reopen it, and lo and behold the math renders properly. It does a particularly poor job if you start editing a cell before all the math is rendered. I can't do anything about this as again it's an eternal program.

FWIW the equation you pasted above renders perfectly on my machine, which is Windows 10, Chrome 64. It also looks good in my local copy of the PDF, the Jan 26, 2018 version.

**Comment by spradlig** [comment]
I'm viewing it directly on Github (static notebook). The PDF does look correct for this particular example. I've been using the web version exclusively but should probably move to the PDF.

I'm using Ubuntu 16.04 Desktop (64 bit) + Chrome.

**Comment by rlabbe** [comment]
I'm going to close this, there is nothing I can do about the way github renders notebooks.
