### ISSUE TITLE
Incorrect Formatting.

### ISSUE THREAD

**Issue by MickeyM79** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#209]
In the attached screen capture, the matrix representation of B is a little misleading.  The rendering looks like B is equal to [ 82 ] not [8  2].  

Additionally, am I misunderstanding the concept, or should [x y] and [8 2] be column vectors not row vectors?

![image](https://user-images.githubusercontent.com/288259/35784867-c1fe6910-09e1-11e8-9265-8f18c736d27a.png)

**Comment by rlabbe** [comment]
As far as I can tell from this write up, this is an artifact of GitHub's poor rendering of LaTeX. I have no control over that. I do not see it in the browser or PDF.
