### ISSUE TITLE
Questions on matrix indexing

### ISSUE THREAD

**Issue by penny4860** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#211]
@rlabbe /cc @mmmmoo

The figure below illustrates the transiton matrix in [chapter14](https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/14-Adaptive-Filtering.ipynb). I'm confused about the matrix indexing here.

![image](https://user-images.githubusercontent.com/7403396/36376975-8fef0956-15b8-11e8-8b90-14057b82d24d.png)

Usually, matrix elements are represented by ``M[row, column]``. But is it ``M[column, row]`` here?

**Comment by rlabbe** [comment]
that's a typo. I'll fix it.

**Comment by rlabbe** [comment]
Finally fixed.
