### ISSUE TITLE
wording problem in Ch10 UKF

### ISSUE THREAD

**Issue by Xiaohong-Deng** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#212]
At the end of _The Unscented Transform_, there is a sentence
> the unscented transform estimates the mean and covariance of a Gaussian passed through an arbitrary, nonlinear function and produces another Gaussian from the transformed points.

I'm not a native so I might be wrong. The sentence gives me an impression that the unscented transform estimates the mean and covariance of the Gaussian before the transformation (the input to the nonlinear function). But the fact is it first transforms the sigma points, then estimates the mean and covariance of the transformed Gaussian (an approximation to the precise result produced by the nonlinear function) based on those transformed sigma points by calculating weighted sums. Thus produces the new Gaussian.

**Comment by rlabbe** [comment]
You are right. It takes an arbitrary probability distribution (which could be a Gaussian), sampled with 2N+1 points plus corresponding weights, passes them through the transform, and returns Gaussians (mean and covariance) of each transformed point. I'll work on the wording, then close this.

**Comment by rlabbe** [comment]
fixed and closed.
