### ISSUE TITLE
Ch2: Pseudocode and train_filter are a bit fuzzy

### ISSUE THREAD

**Issue by Xiaohong-Deng** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#214]
In section [The Discrete Bayes Algorithm](http://nbviewer.jupyter.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/02-Discrete-Bayes.ipynb#The-Discrete-Bayes-Algorithm)
There is a block of pseudocode, the update step is as follows

> Update
> 
> 1. Get a measurement and associated belief about its accuracy
> 2. Compute residual between estimated state and measurement
> 3. Determine whether the measurement matches each state
> 4. Update state belief if it matches the measurement

I know that in Kalman Filter we need to explicitly compute the residual, but until this point in the book the update step is about likelihood prior multiplication while the predict step is about covolution. There is no residual needed to be computed. Would reader be confused by the pseudocode?

---

In section [Simulating the Train Behavior](http://nbviewer.jupyter.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/02-Discrete-Bayes.ipynb#Simulating-the-Train-Behavior)
The for loop in the definition of `train_filter` is as follows
```python
for i in range(iterations):
  robot.move(distance=move_distance)
  m = robot.sense()
  if do_print:
    print('''time {}: pos {}, sensed {}, '''
              '''at position {}'''.format(
                i, robot.pos, m, track[robot.pos]))

  likelihood = lh_hallway(track, m, sensor_accuracy)
  posterior = update(likelihood, prior)
  index = np.argmax(posterior)
  if i < iterations - 1:
      prior = predict(posterior, move_distance, kernel)       

  if do_print:
      print('''        predicted position is {}'''
            ''' with confidence {:.4f}%:'''.format(
            index, posterior[index]*100))            
```
The first problem is a wording problem. "predicted position is ..." and the corresponding printed value is the posterior. By definition or by reading the code, posterior is our best estimate of the current position of the object given the movement and the position reading of the senor. Neither it was a prediction before we had the position reading (it was computed after we had the reading) nor a prediction of the position in the next time step (that was prior computed in the if statement right before `if do_print:`).

Perhaps we are better off with "estimated position is ..."?

The second probelm is about the first iteration of the for loop. The prior is initialzed assuming robot starts at position 0, which is how robot is initialized. In the first iteration, robot first makes a move, then we access its position reading from the sensor. But the code only incorporates the position information into the prior, ignoring the movement. Thus in a noisy environment, the first a few posterior are way off the ground truths.

Perhaps `prior = predict(posterior, move_distance, kernel)` should be inserted before the for loop? In that case, the robot moves as many times as the prior is calculated.

**Comment by rlabbe** [comment]
I agree; I have fixed this.
