### ISSUE TITLE
ch12: seems a typo in importance sampling derivation

### ISSUE THREAD

**Issue by Xiaohong-Deng** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#215]
In section [Importance Sampling](http://nbviewer.jupyter.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/12-Particle-Filters.ipynb#Importance-Sampling) we transform the integral
![imp_samp_integral](https://user-images.githubusercontent.com/3221403/37494591-7203839c-28e4-11e8-8c85-09ff85b12a59.gif)
to the discrete summation
![imp_samp_sum](https://user-images.githubusercontent.com/3221403/37494656-cf32da90-28e4-11e8-9c85-81c2c802c8a4.gif)
Then it is simplified a bit and is pointed out this is an equation that was given before. I suppose what was given before is
![particle_weighted_mean](https://user-images.githubusercontent.com/3221403/37494744-351d9d90-28e5-11e8-9d26-a002fea64b6b.gif)
in section [Compute the State Estimate](http://nbviewer.jupyter.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/12-Particle-Filters.ipynb#Computing-the-State-Estimate)

What is missing here I think is pointing out the assumption that particles are drawn from a uniform distribution, so q(x) = 1/N and **1 / N** is missing in the discrete summation here.

**Comment by rlabbe** [comment]
Yup. Fixed.
