### ISSUE TITLE
Fat tails in Chapter 3 is not quite right!

### ISSUE THREAD

**Issue by violapaul** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#217]
Love the book,  and I recommend it to folks learning the area.

In Chapter 3 you discuss fat tails,  and it is an important concept.

The example you use of filtered exam grades (to include only values between 0 and 100) is perhaps not the best of fat tails.  Typically fat tails refers to data that has a *wider* range of values than would be expected from a Gaussian.  I might argue that the clipped/filtered grades have a *narrower* range of values,  not wider.

First, there are two ways of doing this, and the distribution you graph using this code:

```
xs = np.arange(10, 100, 0.05)
ys = [gaussian(x, 90, 30) for x in xs]  # variance = 30 (std = 5.5)
plt.plot(xs, ys, label='var=0.2')
plt.xlim(0, 120)
plt.ylim(-0.02, 0.09);
```

assumes that the data is **filtered** if the Gaussian value is higher than 100 or lower than 0.  More realistically you'll get a bunch of people with 100's (if the mean is really 90).   Something more like computing the histogram of data generated this way:

```
n_90_30 = scipy.stats.norm(90, math.sqrt(30))   # variance = 30
raw_values = n_90_30.rvs(size=10000)
filtered = [i for i in raw_values if i >= 0 and i <= 100]
clipped = [min(100, max(0, i)) for i in raw_values]
# For comparison
u_10_10 = scipy.stats.uniform(loc=80, scale=20) # stdev of 5.8 (ish)
uniform_values = u_10_10.rvs(size=10000)
```

Computing some statistics (and plotting if you please):

```
def print_stats(vals):
    bins = np.linspace(0, 200, num=100)
    plt.hist(vals, bins=bins)
    print "mean:", np.mean(vals), ", std:", np.std(vals), ", kurtosis:", scipy.stats.kurtosis(vals)

print_stats(uniform_values)
print_stats(raw_values)
print_stats(clipped)
print_stats(filtered)

mean: 90.1139025854 , std: 5.80005966485 , kurtosis: -1.21342327804
mean: 90.001792778 , std: 5.454550317 , kurtosis: 0.0166843069841
mean: 89.9321827218 , std: 5.29939161555 , kurtosis: -0.27101880485
mean: 89.6090233479 , std: 5.0623159724 , kurtosis: -0.219036862955
```

For the clipped/filtered data sets the kurtosis is *negative*,  implying that they are more like the uniform distribution,  and so **they do not have fat tails**.

**Comment by rlabbe** [comment]
I agree, I'll make the fix. Thanks.
