### ISSUE TITLE
Contents page, enhancement request!

### ISSUE THREAD

**Issue by peepo** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#223]
Is there a Contents page?

preface                                                         1
chapter 1               the g-h filter                    15
chapter 2               discrete Bayes filter        55

usually these can be linked to one-click to the chapter of interest

I did not find in .pdf version, using low-end chromebook!!

tx

**Comment by peepo** [comment]
weirdly,having read your response, when I read offline, the chapters are bookmarked.
ie when the .pdf is auto-opened the bookmarks are not present.
either happen in the browser, like all else.
so I take this to be a system fault.
apologies and thanks again!
~:"

**Comment by rlabbe** [comment]
I've added an explicit table of contents to the book so you don't have to use the bookmarks.
