### ISSUE TITLE
Reorder UKF - start with an example

### ISSUE THREAD

**Issue by rlabbe** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#225]
I've gotten comments that someone can't figure out how to use the UKF, which is a bit puzzling to me since it is so easy. Probably all the stuff about sigmas and weights throw people off. Start with a simple example, then explain the theory.

**Comment by azeemiqbal123** [comment]
I agree

**Comment by rlabbe** [comment]
Fixed
