### ISSUE TITLE
Application in a project

### ISSUE THREAD

**Issue by Krutarth0204** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#229]
I working on a project based on multivariate regression and I want to apply Kalman filter to it. 
I have the required data for creating the process and measurement noise matrices and the input is not exactly a function of time but the input data is time series. The governing equation goes as - 
 Output = b0 + b1x1 + b2x2 + b3x3 +......
The input is x1,x2,x3...in time series and the b values need to be updated at each step.
Would the Multivariate Kalman filter work or is there anything else that you suggest.

**Comment by rlabbe** [comment]
That seems to violate the markov property, so I wouldn't think so, unless you can express the KF state purely in terms of the previous state.
