### ISSUE TITLE
Chapter 6, the covariance between two noise should be zero

### ISSUE THREAD

**Issue by trooperli** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#232]
I am reading Chapter 6, and in the section of computing Q for white noise, the result is:
[[0.588, 1.175],[1.175, 2.35]]. I don't know how this is obtained, but I believe the cross correlation between two noise should be zero rather than 1.75. Please correct me if I miss anything.

Thanks,
Greg

**Comment by rlabbe** [comment]
The code is correct. Noise in velocity means there will be noise in the position, thus they are correlated. Section 7.3 derives the equations that govern this computation. Chapter 6 is a bit tough going, as I have to introduce a lot of stuff all at once while trying to minimize the mathematical presentation, which then leads to questions like yours. I'll leave this open for a bit to remind myself to add some verbiage the first time this pops up to point out the correlation exists.
