### ISSUE TITLE
Request: Please write a book on sensor fusion algorithms

### ISSUE THREAD

**Issue by mohse-n** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#236]
First of all, thank you. Before coming across your book, I'd been searching the "literature" for a lucid and application-oriented of Kalman filter for a long time. It's crazy how obfuscated most (if not all) academic resources of Kalman filter are, at least to a beginner like me.
All I want now is to read a similar treatment of sensor fusion algorithms, including EKF (for example, combining attitude estimates from computer vision and IMU) and also Madgwick, Mahony, etc. I know it would aid many researchers, grad students and hobbyists.

**Comment by rlabbe** [comment]
Thanks. I don't have a ton of knowledge about that topic, or, to be honest, interest in pursuing it at this time.
