### ISSUE TITLE
pip install filterpy at command line does not install for book

### ISSUE THREAD

**Issue by gwshaw** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#237]
I tried installing filterpy for both python2 and python3 at the command line in OSX, but the first cell in the preface (http://localhost:8889/notebooks/00-Preface.ipynb) always failed with an error when trying to run it. I found the following was needed:
``` python
#format the book
!pip install msgpack
!pip install filterpy
from book_format import load_style
load_style() 
```
and this worked just fine.

**Comment by rlabbe** [comment]
This is going to be a problem with your installation, not the book. I've gotten issures from OSX users before - i think what happens is when they install from the command line it uses the system python, not the python they are using to run the notebook. I can't imagine why you'd need msgpack except for jupyter notebook - it uses it for communication between the browser and kernel. So, something in your install is wrong. I can't debug that, nor offer much advise since I don't use or have access to OSX.

**Comment by gwshaw** [comment]
If the above works on other systems, and you no longer need to explain that the user needs to install filterpy, why not make the book more encapsulated by putting the filterpy pip command in the first cell of the book? Or in a separate config cell if you like. Reduces the amount of externally documentation to execute the book.

**Comment by rlabbe** [comment]
I don't know what channel they want to use, or version. Also, the kernel that you are running can be completely different from the installation used to launch the notebook, so !pip install doesn't work in all cases. If you are using Conda, and don't have the requirements of FilterPy installed, then you end up with them pip installed, not conda installed. 

And then you end up with a ton of text in your notebook:

Requirement already satisfied: sympy in c:\anaconda3\envs\py27\lib\site-packages
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Requirement already satisfied: filterpy in c:\users\rlabbe\dropbox\filterpy
Requirement already satisfied: numpy in c:\anaconda3\envs\py27\lib\site-packages (from filterpy)
Requirement already satisfied: scipy in c:\anaconda3\envs\py27\lib\site-packages (from filterpy)
Requirement already satisfied: matplotlib in c:\anaconda3\envs\py27\lib\site-packages (from filterpy)
Requirement already satisfied: backports.functools-lru-cache in c:\anaconda3\envs\py27\lib\site-packages (from matplotlib->filterpy)
Requirement already satisfied: six>=1.10 in c:\anaconda3\envs\py27\lib\site-packages (from matplotlib->filterpy)
Requirement already satisfied: pytz in c:\anaconda3\envs\py27\lib\site-packages (from matplotlib->filterpy)
Requirement already satisfied: cycler>=0.10 in c:\anaconda3\envs\py27\lib\site-packages (from matplotlib->filterpy)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\anaconda3\envs\py27\lib\site-packages (from matplotlib->filterpy)
Requirement already satisfied: python-dateutil>=2.1 in c:\anaconda3\envs\py27\lib\site-packages (from matplotlib->filterpy)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\anaconda3\envs\py27\lib\site-packages (from matplotlib->filterpy)
Requirement already satisfied: setuptools in c:\anaconda3\envs\py27\lib\site-packages (from kiwisolver>=1.0.1->matplotlib->filterpy)
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

You can suppress that with %%capture, but then you can't see if there are errors or conflicts. 

Without that, to generate the PDF I then have to modify my scripts to strip all that crap out. And if someone wants to view the notebook online they also have to see and scroll past it. 

Also, Filterpy is going to version 2.0 around the end of the year, to coincide with Numpy/SciPy dropping 2.7 support. 1,x will still support 2.7 (though I won't maintain it any longer, probably). 
Finally, it is a security risk, though that is fairly far fetched.

Here's a really long github issue showing all the frustrations people have had with trying to do this
https://github.com/jupyter/notebook/issues/2359

And Jake Vanderplas' write up of the issues you face trying to do this:
https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/

In the end I'll end up with issues reading "filterpy works in the notebook but won't import from the command line'! In other words, this doesn't fix the issue of the user having multiple install paths, it just masks it for a bit. 

So, for all those reasons, I am not a fan of this. The developers of Jupyter are aware of the issue and plan to address it eventually. In the meantime I'd prefer to keep my book clean and not try to solve installation issues.

**Comment by gwshaw** [comment]
Thanks for the detailed response. Looks like I've done many things wrong in trying to solve the problem, and google did not save me.
