### ISSUE TITLE
Table of Contents Hyperlink is not local

### ISSUE THREAD

**Issue by gwshaw** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#238]
When running the notebook locally, e.g.:
http://localhost:8888/notebooks/Projects/Kalman-and-Bayesian-Filters-in-Python/07-Kalman-Filter-Math.ipynb
the link for the Table of Contents at the top of each page points to:
http://nbviewer.jupyter.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/table_of_contents.ipynb
rather than localhost. Clicking on the Juypter icon will go to the correct host, so the problem is only error prone and not blocking the navigation.

**Comment by rlabbe** [comment]
Fixed.
