### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by gwshaw** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#241]
In the example in  03-Gaussians.ipynb under Why Square The Differences, I get the following error:
/anaconda3/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)

in the code, this change is required `labelbottom=False`

**Comment by rlabbe** [comment]
Fixed.
