### ISSUE TITLE
Algorithmic issue regarding Particle Filters

### ISSUE THREAD

**Issue by reletreby** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#245]
Hi Mr. Labbe,

I just have a quick question regarding the way you implemented the "update" function in the particle filter chapter. You started with filling the weights with ones "weights.fill(1)" for every new iterations, however, I think this is only possible if you resample at every iteration. Otherwise, there has to be a recursive relationship between the weights of the previous round and the weight of the current round, i.e., the current weight should be the multiplication of the previous weight by the probability of the measurement given the state of the particle.

Thank you Mr. Labbe for such a great book and repository. 
Rashad

**Comment by rlabbe** [comment]
I think you are correct. This is a holdover from an early version of the book where I resampled on every iteration.
