### ISSUE TITLE
Pi calculation using Monte Carlo Method in Ch. 12

### ISSUE THREAD

**Issue by bagustris** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#246]
In Ch.12, you demonstrated how to calculate pi using Monte Carlo method. However, I think I found mistake although the result is correct. In python code, you use

`pi = area * (pts_in_circle/N)`

If we change the value of area, the value of pi will change, it should not change regardless the value of area. From the derivation (by comparing area of circle and square), the correct formula is "pi = 4 * (area_of_circle/area_of_rectangle)". So, the python code should be,

`pi = 4 * (pts_in_circle/N)`

And we can ignore the `area` variable.
CMIIW.

**Comment by rlabbe** [comment]
Thanks, fixed.
