### ISSUE TITLE
Convert to Python 3.5+

### ISSUE THREAD

**Issue by rlabbe** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#249]
NumPy ecosystem is leaving 2.7 behind after the end of the year, and many have gone to 3.5+. Do the same, largely to get that lovely @ operator!

**Comment by x1angli** [comment]
Really expecting the "@" operator!  
What other improvements are we expecting?

**Comment by rlabbe** [comment]
Also update all of the minimum requirements in book_format.py for more recent versions of numpy, matplotlib, IPython, etc. I'm dubious old versions of other packages support Python 3.5, and I don't want to be supporting old versions forever.

**Comment by teyrana** [comment]
Is there a python3 branch in progress that we could run ?
(granted, I suppose I'd be a beta tester at this point)

Supposed one is running a python3.x interpreter, would you be open to PRs to forward-port the notebooks?

**Comment by rlabbe** [comment]
Everything runs in 3.x as well as 2.7. I develop the project in 3.7, and use 3.7 at work every day. I see Anaconda (the distribution I use) has finally released 3.8, so I need to run regression tests on that. What the software doesn't do is use features in 3.5+, such as the matmul operator @ or f-strings, probably the two most important/useful features for this project, and the point of this issue.

I created a local branch for 3.5, but I don't think I have pushed it. I did that awhile go, it is no longer current. I ran into a real problem. A lot of my code works for single dimensions - you can pass in float and use float for the state and covariance. In other places you can use single dimension arrays. matmul only supports matrix matrix operations. So I ended up having to use dot everywhere anyway.  It's frustrating because you can write dot(x, 3), dot(x, [3]), dot(x, array([[3]]), and all of that works fine, but you can't write x@3. I don't recall all the details, but I think I remember getting burned in unexpected places like computing weights for particle filters.

So I have to either stick with @, or revise what all of the classes can take for data. There's nothing 'wrong' with using dot, it is just a bit less readable.

I'd really like to use f-strings in the notebook. But I still get questions from people using 2.7. Should I go to 3.6 and cut even more people off? Honestly, I'd love to, as f-strings are more concise and it is easier to fit things on one line. But Ipython 6.x supports 3.3+, 7.x supports 3.4. They haven't deprecated 3.4 yet, should I? 

I'd probably not want pushes to update FilterPy; I think that needs a very cohesive plan and testing with significant additions to the unit tests.

Pushes for the notebooks seems more feasible, but even there I'd want a cohesive release. It some notebooks use @, others use dot, some use print with argument, some use format, some use f-strings, well, it is just that much more to make things hard to read and understand. I would want to strip every use of dot from the notebooks, and perhaps have an appendix or sidebar for cases where FilterPy doesn't use dot (if I decide to still support that). It's not enough to just change code; for better or worse I made some effort to teach the rudiments of NumPy, so a bit of that text needs to be changed as well. Since this is a pedagogical project, I'd want all the supporting code to follow the same style. I 'hide' a bunch of code in imports that support the chapter. My hope/expectation is that the person who really wants to learn the topic fully are examining the code via ?? magic or just opening the files. So it's a lot of work that no one has ever shown so far when pushing changes. which are always very helpful but also very small in scope.

I've been holding off while watching what other major packages do. I feel I can justify a newer Python version for my tiny project if the big projects are doing that. I see scikit-learn now requires 3.6+ with the release 0.23. Looks like matplotlib has required 3.6+ since matplotlib 3.1. So, I think I have talked myself in making the minimum version be 3.6. I don't anticipate broad changes to the material, so those stuck on earlier versions of Python for whatever reason can still use the older notebooks, and refer to the issue tracker for whatever bugs anyone has found. 

Honestly, I've been putting it off because it is so much work, and it is an endless fight just trying to keep up with the endless infrastructure changes in the ipython and jupyter space, but it really is time to make a clean break and move to 3.6. Hang on!

**Comment by rlabbe** [comment]
Okay, so this is done for the book! FilterPy is still supporting 2.7, I'll work on that next, as it is a much larger change. 

We support Python 3.6+ only. I do not anticipate chasing versions anymore unless there are breaking changes in other libraries (numpy, matplotlib, etc) that cause the book to malfunction. 

I have created two releases. Release 1.1 is the book prior to this change. If you are stuck on an older version of Python for any reason, you can checkout that release and use it. I will not be backporting any fixes to that release. I *may* accept pushes if some org decided to take that over for some reason, but I doubt it. I just don't have time for this.

Release 2.0 is for the current Python 3.6+ support. I do not anticipate any more releases; most people work from master, so I'll just keep pushing changes as needed. If there are major changes, which I don't currently anticipate, then perhaps a new version number will be warranted.
