### ISSUE TITLE
filterpy needed before chapter "Companion Software" in 00-Preface

### ISSUE THREAD

**Issue by solarjoe** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#260]
The chapter 00-Preface explains how to apply the formatting using the first cell. At some later point in the chapter _Companion Software_ it explains that the module `filterpy` is needed and how to install it.

But since `test_filterpy_version()` in `book_format` already needs the module the cell throws a `ModuleMissing` error if the module is not found.

You could mention earlier that the module is needed and how to install it.

**Comment by rlabbe** [comment]
I modified the function to try to import all the required packages and print instructions if they are not installed. This avoids exceptions occurring in the header, but prints useful information on what to do instead.
