### ISSUE TITLE
Keep getting "not defined" throughout notebook

### ISSUE THREAD

**Issue by atyshka** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#261]
Throughout this notebook when I try to run code I keep getting undefined errors. For example, in the g-h filter chapter, when running the final code I get 

`---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-951235a208ef> in <module>
     13 
     14 # uncomment to run the filter and plot the results
---> 15 book_plots.plot_track([0, 11], [160, 172], label='Actual weight')
     16 data = g_h_filter(data=weights, x0=160., dx=1., g=6./10, h=2./3, dt=1.)
     17 plot_g_h_results(weights, data)

NameError: name 'book_plots' is not defined`

I'm not sure exactly how jupyter notebooks are supposed to work but I'm assuming the required imports should be under the hood. What's going wrong?

Python 3.6, Conda

**Comment by atyshka** [comment]
Update: Code works without errors if I choose to "run all cells" but then all the plots disappear!

**Comment by rlabbe** [comment]
This is just how jupyter notebooks work. You have to run cells in order, and they do not magically know what to import or when.
