### ISSUE TITLE
Improvements for 01-g-h-filter.py

### ISSUE THREAD

**Issue by solarjoe** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#262]
The section _Exercise: The Effect of Acceleration_ does state value for `noise`, `g`, `h`. It should also state other values that are needed to display the mentioned effect so the reader does encounter it. 

Else one has to look at the solution as the values from the previous cell are used.

```
zs = gen_data(x0=10., dx=0., count=20, noise_factor=0, accel=2.)
data = g_h_filter(data=zs, x0=10., dx=0., g=0.2, h=0.02)
```

Additionaly, there could be a hint before on how to limit the x axis to a specific range to emphasize the region with the effect.

**Comment by rlabbe** [comment]
The other values don't matter. Set acceleration to 9 for example, and the plot looks the same, just the y axis scales differently. I kind of want people to start exploring, not get predetermined results.  I've added verbiage encouraging the user to experiment.
