### ISSUE TITLE
Typo, section 14.4.1 Continuous adjustment. I thought S was covariance of residual, not of measurement

### ISSUE THREAD

**Issue by stevegilbert** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#263]
In section 14.4.1 "Continuous adjustment" it says:

> where $\mathbf{y}$ is the residual and $\mathbf{S}$ is the measurement covariance, which has the equation

$$\mathbf{S} = \mathbf{HPH^\mathsf{T}} + \mathbf{R}$$

Shouldn't this say that S is the covariance of the residual? (Some authors refer to S as the covariance of the innovation.) I thought that R is the measurement covariance matrix.

**Comment by rlabbe** [comment]
Yup. Fixed.
