### ISSUE TITLE
Translating to Arabic, as a book or  jupyter notebooks

### ISSUE THREAD

**Issue by engyasin** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#265]
Hi Mr @rlabbe 

I have a suggestion: to translate your work into arabic langauge,
and I intend to make a repo here in github so people can view it on nbviewer (or some blog).
is that okay?

**Comment by rlabbe** [comment]
Yes, the CC rights allow for that, so long as you give attribution.

**Comment by rlabbe** [comment]
I'm closing this, but feel free to respond if you have any further questions.

**Comment by engyasin** [comment]
@rlabbe , Thanks , I will check the creative commons rules, and make sure to apply them, 

**P.S**: I started [here](https://engyasin.github.io/kalman_book/)
