### ISSUE TITLE
Stochastic Differential Equation

### ISSUE THREAD

**Issue by LorenzoBottaccioli** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#266]
Hi I'm tring to learn the paratmeter (x_1,x_2,x_3,x_4) of the following continuous stochastic differential equation systems:

dTi = 1/x_1 * (Te −Ti) * dt+ 1/x_2 * P_hdt+ x_3*dt+ sigma_e * dω_i

dTe = 1/x_4 * (Ti −Te) * dt+(Ta −Te) * dt+ sigma_e * dω_e

I have discrate time measurment with equation:

Yk=Tik+ek

ek is Gaussian white noise.

Is it possible to implent a filter with filterpy in order to estimate such parametr? Wich is the most suitable?

Best

**Comment by rlabbe** [comment]
Please don't open duplicate issues across multiple projects. I'm closing this one and responding to the one in FilterPy.
