### ISSUE TITLE
Request: varying time interval Kalman Filter

### ISSUE THREAD

**Issue by atyshka** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#270]
First of all, I'd like to thank you for such a great, comprehensive guide on Kalman filtering! This is by far the best resource I've found so far and I'm currently creating a c++ library from what I've learned. One thing that I didn't see covered is how to work with data that has a varying dt. I'm trying to work with neural nets which, unlike a camera, have varying runtimes and I'm wondering how I should set up a filter for this scenario. This seems like a reasonably common scenario and it would be great if you could cover it. Thanks!

**Comment by rlabbe** [comment]
It's already in the book, chapter 8, "Nonstationary Processes"

**Comment by atyshka** [comment]
Apologies, that definitely covers what I need, it just wasn't immediately apparent from the title.
