### ISSUE TITLE
Chapter 06: Error in "predict" code

### ISSUE THREAD

**Issue by stefsietz** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#273]
> ###  Design the Process Model
> 
> The next step is designing the *process model*. It is a mathematical model which describes the behavior of the system. The filter uses it to predict the state after a discrete time step. We do this with a set of equations that describe the dynamics of the system.
> 
> In the univariate chapter we modeled the dog's motion with
> 
> $$ x = v \Delta t + x_0$$
> 
> We implemented this as follows:
> 
> ```python
> def predict(pos, movement):
>     return gaussian(pos.mean + movement.mean, 
>                     movement.var + movement.var)
> ```

I am pretty sure that the second parameter of the gaussian() function should be pos.var + movement.var instead of  movement.var + movement.var.

**Comment by thorstenwagner** [comment]
Me too.

**Comment by rlabbe** [comment]
Fixed, thanks!
