### ISSUE TITLE
ch. 6 Why covariance matrix P equals E[x * x.T]

### ISSUE THREAD

**Issue by Xiaohong-Deng** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#274]
Under [Prediction Equations](https://nbviewer.jupyter.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/06-Multivariate-Kalman-Filters.ipynb#Prediction-Equations) it's stated that **x** is the mean of the Gaussian and **P** is the covariance matrix. Also it states that **P** is equal to ![cov_p_exp](https://user-images.githubusercontent.com/3221403/50742152-54b80b80-1242-11e9-95be-ad222f48daaa.gif).

I think x * x.T is an outer product of itself. Isn't this expectation just a constant 2 by 2 matrix with **x** being mean? The elements of the matrix should be product of means of position and velocity. They are not variances or covariances of the Gaussian. 

Let's assume **x** is random variable. Shouldn't **P** be ![cov_p_exp_2](https://user-images.githubusercontent.com/3221403/50742234-2850bf00-1243-11e9-839c-355f8ebee4f4.gif) unless mean here is a zero vector. Is mean assumed to be zeros?

I'm confused here. May I get some clarification?

PS: This doesn't affect the correctness of
![transition_p](https://user-images.githubusercontent.com/3221403/50742455-5edc0900-1246-11e9-9ad7-9ed49861d272.gif) if you use mu as the mean vector and **x** as the random variable, starting from ![cov_p_exp_2](https://user-images.githubusercontent.com/3221403/50742234-2850bf00-1243-11e9-839c-355f8ebee4f4.gif). You will eventually get ![tran_p_bar](https://user-images.githubusercontent.com/3221403/50742515-3b658e00-1247-11e9-9643-2c748c15abfc.gif) with **F** prepended and **F.T** appended.

**Comment by rlabbe** [comment]
Fixed.
