### ISSUE TITLE
Minor typo in 04-One-Dimensional-Kalman-Filters

### ISSUE THREAD

**Issue by WillieMaddox** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#276]
Under "Predictions with Gaussians" the line,

...confidence should get smaller (variance gets larger). $\mu_{f_x}^2$ is the amount of uncertainty added...

should read,

...confidence should get smaller (variance gets larger). $\sigma_{f_x}^2$ is the amount of uncertainty added...

I think?

**Comment by rlabbe** [comment]
Indeed! Fixed.
