### ISSUE TITLE
In Chapter 7, should not it be "Taylor expansion" instead of "Euler expansion"

### ISSUE THREAD

**Issue by hristo-vrigazov** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#277]
![image](https://user-images.githubusercontent.com/14914140/52438277-9548c480-2b21-11e9-8817-0a4c3721d581.png)

Should not it be "Here are the first 3 terms of the *Taylor* expansion of y" instead of "Euler expansion"?

**Comment by ejuarezg** [comment]
I agree with @hristo-vrigazov

**Comment by rlabbe** [comment]
fixed
