### ISSUE TITLE
Incorrect Variance Value in Chapter 3

### ISSUE THREAD

**Issue by abedshantti** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#282]
The variance for the provided numpy array example (page 96 of the PDF) x=[3,-3,3,-3] is incorrect in the Jupyter Notebook and the pdf file. The variance is meant to be 36/4 = 9, but in the book it is saying 12/4 =3 which is not correct since the differences were not squared. 
![error](https://user-images.githubusercontent.com/48472517/55545399-67b96b00-56cd-11e9-8fb6-922291ebd9cf.PNG)

**Comment by abedshantti** [comment]
I understand that you are considering the absolute value rather than calculating the variance. But I think it should be made clear that the absolute value which is 3 is different than the variance of the dataset which is equal to 9.

**Comment by rlabbe** [comment]
I don't really follow your objection. We are allowed to use any formula for variance, we are not constrained to Gauss' choice. It is not required to equal the square, that is just the formula that Gauss choice and which works 'usually'.
