### ISSUE TITLE
Ch 10 interpretation of Kalman gain typo?

### ISSUE THREAD

**Issue by mbloem** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#283]
Is there a typo in the boxed portion of the interpretation of the Kalman gain for the EKF in chapter 10 shown in the screenshot below? I was thinking that a stronger/larger belief in the measurement would correspond to a "smaller" $\mathbf{P}_z$, so the boxed portion should be flipped. This would also make more sense to me as a stronger belief in the measurement (with belief in state held constant) would lead to a larger gain/weight on the measurement residual. 

![image](https://user-images.githubusercontent.com/6723387/55642204-74a19180-5795-11e9-9c2a-4df6622bab17.png)

**Comment by rlabbe** [comment]
P_z, the denominator, is the measurement covariance. P_xz, the numerator is the cross covariance of measurement and state. Probably I need a better term than 'state' in the numerator.
