### ISSUE TITLE
Handling of case where missing some but not all elements of observation vector at a time step

### ISSUE THREAD

**Issue by mbloem** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#284]
Great book and Python package! I'm really appreciating it!

I'm working to re-implement the multi-modal UKF described in [this publication](https://dspace.mit.edu/handle/1721.1/80334). One issue I'm having is that while I usually will receive "full" or "complete" observations with all 4 elements of the state (X, Y, speed, heading), I also often receive "incomplete" observations with only 2 or 3 of these. X and Y are always included, but speed and/or heading are often missing. For now I'm treating incomplete observations as completely missing, but I'm sure I'll get much better performance if I can use these incomplete observations. I am not sure how best to use them (in general and with FilterPy).

A few ideas:
- Just use the prediction for the un-observed states. Only do the update for the observed states, but do so in a way that only updates the observed component of the state. Looks like I might be able to do this with just a change to the residual_z function and also how the dot product of K and y is computed (to handle when we have missing components of y).
- Maintain different observation functions and measurement noise matrices $R$ and other UKF parameters/matrices for when different components of the state are returned (one for complete measurements, one for X & Y, one for X & Y & heading, and another for X & Y & speed). Use whichever is appropriate given the current observation. 

Any help is appreciated - thanks!

**Comment by mbloem** [comment]
Updates:
- I tried the first idea, simply by adjusting the residual function to return 0 for any missing components of the observation. This works out okay...
- I'm having better luck by just completely ignoring the speed & heading observations (i.e., by specifying an observation function $h$ that only returns X and Y). 
- The speed & heading are not only missing fairly often but also seem to be highly unreliable at low speeds. I might try actually the first idea, but also ignoring these two at low speeds.

**Comment by rlabbe** [comment]
You are allowed to modify H and R on every call to support exactly this problem. If speed and heading are very unreliable, you need to reflect this in R so their input is sufficiently discounted.

I'm going to close this, as the questions are old; you can reopen if follow up is needed. This is getting pretty far from 'school book' Kalman filters and into the real problems we face as practitioners, which I admittedly don't cover much in the book.
