### ISSUE TITLE
Chapter 7 says that dx/dt = dv/dt

### ISSUE THREAD

**Issue by huberemanuel** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#285]
I think that this statement is not correct, maybe the author was trying to do a comparison, but I think this could be improved.
The integral of velocity gives position, and the integral of acceleration gives velocity.
![image](https://user-images.githubusercontent.com/6238718/55648444-babb1d00-57b6-11e9-88c6-fbc665589533.png)

**Comment by dimidagd** [comment]
Please revise calculus, the **derivative** of position is the velocity, and the derivative of velocity is acceleration. The equation is following the chain rule, in other words dx = dx*dt/dt = u *dt, although the limits in the second integral should probably be t0 to t0+Δt 

All the best!

**Comment by huberemanuel** [comment]
Sorry, I made a mistake on my question, but it stills not making sense to me, how can the integration of position be equals to acceleration (integration of velocity)?

**Comment by dimidagd** [comment]
It is not an integration of the position, it’s an integration of the unit function.  final position minus starting position. If you go on with the math I mentioned it should make sense.
