### ISSUE TITLE
Chapter 2 "set"

### ISSUE THREAD

**Issue by r0f1** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#288]
In Chapter 2 it says:

> Given a set of numbers, such as {1, 2, 2, 2, 3, 3, 4}, the mode is the number that occurs most often. For this set the mode is 2. A set can contain more than one mode. The set {1, 2, 2, 2, 3, 3, 4, 4, 4} contains the modes 2 and 4, because both occur three times.

In these sentences the word `set` should be replaced by `list`. A set cannot contain an element more than once. A list can.

**Comment by rlabbe** [comment]
Fixed, thanks!
