### ISSUE TITLE
The g-h Filter: off-by-one error in scale example

### ISSUE THREAD

**Issue by Gluttton** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#29]
According to description of the example weight have to gain of 1 lb per day.

> I hand generated the weight data to correspond to a true starting weight of 160 lbs, and a weight gain of 1 lb per day. In other words one day one the true weight is 160lbs, on the second day the true weight is 161 lbs, and so on.

It means that when weight equal 160 lb at 1-st day it will equal 171 lb at 12-th day:
 1 - 160
 2 - 161
 3 - 162
 4 - 163
 5 - 164
 6 - 165
 7 - 166
 8 - 167
 9 - 168
10 - 169
11 - 170
12 - 171

But on the chart weight at 12-th day equals 172 lb.

![plot](https://cloud.githubusercontent.com/assets/619261/7336152/3cf0a1e0-ebf6-11e4-8af1-ab2c63671119.png)
It looks like [off-by-one error](http://en.wikipedia.org/wiki/Off-by-one_error).

In my opinion correct values of weight should be:
 0 - 160 (today)
 1 - 161 (tomorrow)
 2 - 162
 3 - 163
 4 - 164
 5 - 165
 6 - 166
 7 - 167
 8 - 168
 9 - 169
10 - 170
11 - 171
12 - 172

**Comment by rlabbe** [comment]
You are right. 160 is supposed to start at day 0, so that the first prediction can add 1 lb to get 161 for the first day's prediction. I've made the fix and will be pushing it soon.
