### ISSUE TITLE
3.4.2 Solution: Mean is 3.5

### ISSUE THREAD

**Issue by robertdeml** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#291]
3.4.2 currently has this:
= 1/6 × 1 + 1/6 × 2 + 1/6 × 3 + 1/6 × 4 + 1/6 × 5 + 1/6 × 6
= 1/6(1 + 2 + 3 + 4 + 5 + 6)
= 3

However, the answer should be 3.5

**Comment by rlabbe** [comment]
Not sure when it happened, but this is fixed now.
