### ISSUE TITLE
Ch. 4, KF Animation broken

### ISSUE THREAD

**Issue by richard-roberts** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#293]
More of an FYI than an issue.

The `animations/05_dog_track.gif` appears to be broken in some way. It appears as a missing image when viewing the chapter in Firefox (rendered via the `jupyter notebook` server). Opening the image reveals some kind of visual artifact (screenshot included below). When viewing via [GitHub in the browser](https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/04-One-Dimensional-Kalman-Filters.ipynb), the the artifacted image appears.

<img width="485" alt="Screen Shot 2019-04-18 at 12 08 44" src="https://user-images.githubusercontent.com/14899134/56328415-04523180-61d3-11e9-94dc-64574cff68cb.png">

**Comment by rlabbe** [comment]
Thanks, it is fixed now.
