### ISSUE TITLE
book_format.set_style() warning MatplotlibDeprecationWarning

### ISSUE THREAD

**Issue by haghad** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#298]
Is anybody else getting this error/warning:
![image](https://user-images.githubusercontent.com/44681869/57167301-49798480-6dcb-11e9-94af-db9a60187f38.png)
I'm using a new conda environment dedicated for this book where I've installed the newest version of python (3.7) and the newest versions of the scipy stack and filterpy.

**Comment by rlabbe** [comment]
I fixed this in a check in today, thanks for reporting.
