### ISSUE TITLE
chapter 01-g-h-filter.ipynb - wrong results demonstration for filters with the same data

### ISSUE THREAD

**Issue by afanasyspb** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#300]
Hi! 
Compare the plots in the fields: in [17] (Building a filter) and in [22] ("Solution and Discussion" for g-h filter). They use the same dataset. But if in the previous plot the measurements start at day 1 and "Filter" value goes from 160 (day 0), the latter plot shows "actual weight", "filter" and "measurements" at the step 0. It is better to shift the "filter" and "measurements" values to the Step 1 on the plot, or at least change the "actual weight" value from 160 to 161 at the step 0.
![image](https://user-images.githubusercontent.com/51266015/58749326-71710c00-848d-11e9-8ce0-b89e55ca1062.png)

**Comment by rlabbe** [comment]
Good catch, fixed.

**Comment by fpertl** [comment]
It now appears that the estimates no longer fall between the prediction and the measurement for a given day. While in the plot previously reference in this issue by afanasyspb they do.

**Comment by ydixon** [comment]
Jesus. This was driving me crazy as I'm totally new into this topic. I was scratching my head why we are making estimate using measurement from Tk-1. I'm glad someone mentioned it.

**Comment by rlabbe** [comment]
Fixed via #343.
