### ISSUE TITLE
Most animations broken from line endings change

### ISSUE THREAD

**Issue by bob80333** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#302]
Some of them are subtly broken: the GIF ends too soon like `05_volt_animate` and some are completely broken like `05_dog_track`.  They appear to have been modified in `0e43c1b9aef4242bf794fd5086319b1db496d057` where line endings were changed from CRLF to LF, which probably wasn't supposed to be applied to binary files like GIFs.

**Comment by rlabbe** [comment]
This should be fixed now. Raise a new issue or reopen if it remains.
