### ISSUE TITLE
04-One-Dimensional-Kalman-Filters 

### ISSUE THREAD

**Issue by yukun2016** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#304]
![image](https://user-images.githubusercontent.com/22852074/60794131-ab73b300-a19b-11e9-9f73-2cfba071eeef.png)
![image](https://user-images.githubusercontent.com/22852074/60794146-b0d0fd80-a19b-11e9-8d82-6954e300b9a2.png)
should use?
![image](https://user-images.githubusercontent.com/22852074/60794212-d8c06100-a19b-11e9-944e-4eafdd14fbd4.png)

**Comment by rlabbe** [comment]
Thanks. You are correct. At some point this was fixed, as it sigma now.
