### ISSUE TITLE
01-g-h-filter "actual" plot suggestion

### ISSUE THREAD

**Issue by karthikbmk** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#305]
Hello, I thank you very much for the wonderful notebooks on Kalman Filters ! For the chapter 01-g-h-filter, I have a suggestion - Currently, the "actual" list is initialized as [160, 173], because of which the weights do not appear correctly(an increase of +1 per day) in the plot. 
Please consider changing it to [160, 172].

With [160, **173**]:
![173](https://user-images.githubusercontent.com/8171762/61753761-1c3ae200-adce-11e9-8fa8-30c7ee07fe60.png)

With [160, **172**]:
![172](https://user-images.githubusercontent.com/8171762/61753779-2fe64880-adce-11e9-9426-945ae3282756.png)

**Comment by rlabbe** [comment]
Fixed, thanks.
