### ISSUE TITLE
Question: 01-g-h-filter Excercise: The Effect of Acceleration. Lag error seems to be corrected by changing the value of h.

### ISSUE THREAD

**Issue by deyingk** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#312]
Bellow the excercise, it is commented that "_Note that there is no adjustment to 𝑔 or ℎ that we can make to correct this problem._" 
However, if I change h to 0.5, rerun the code, the lag error seems to disappear. The problem seems to be corrected.
Is there anything I have misunderstood? 
Thanks!

**Comment by froohoo** [comment]
It seems to disappear but if you add something like:
`print(np.array(zs)-np.array(data))`
to the end of the code block, you will see that (without noise present) the prediction always lags the signal. You can keep increasing h, but it will become unstable before the prediction leads the signal.

**Comment by rlabbe** [comment]
I didn't go deep into the math here, but as froohoo states the system will always lag and/or go unstable. There are formal proofs of this, but I felt it was beyond the scope of the book. If it worked, there would be no need for kalman filters.
