### ISSUE TITLE
Computing sigma points with column (or row) vectors of cholesky((n+lambda)*P))

### ISSUE THREAD

**Issue by aserbremen** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#316]
In chapter 10 when calculating sigma points you state: 

> The subscript  𝑖  in  [ sqrt( (𝑛+𝜆)Σ )]𝑖  is choosing the column vector of the matrix.

but when calculating the sigma points you choose row vectors 
```python
sigmas = np.zeros((2*n+1, n))
U = scipy.linalg.cholesky((n+lambda_)*P) # sqrt

sigmas[0] = X
for k in range (n):
    sigmas[k+1]   = X + U[k] # row vector of U
    sigmas[n+k+1] = X - U[k] # row vector of U
```
According to [Merwe](http://www.gatsby.ucl.ac.uk/~byron/nlds/merwe2003a.pdf) on page 7, row or column vectors are okay as I understood. Maybe you could elaborate on that and change either the text or the implementation?

**Comment by rlabbe** [comment]
I'm not 100% sure at the moment. I know why the discrepancy exists between text and code, however. scipy.linalg.cholesky returns upper-triangular by default, and numpy.linalg.cholesky returns lower-triangular by default. I think when I wrote the text I was using numpy, not scipy. If I remember correctly grabbing rows or columns depends on which one you use, but I don't recall the specifics,
