### ISSUE TITLE
Conda warning during kf_bf environment creation

### ISSUE THREAD

**Issue by vsingla2** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#317]
Below message pops up while creating `kf_bf` environment:

`Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.`

This can be fixed by adding pip as one of the dependencies in the `environment.yml` file.

**Comment by rlabbe** [comment]
Fix merged. Thanks!
