### ISSUE TITLE
Discrete Bayes Filter: some examples use non-common data domain

### ISSUE THREAD

**Issue by Gluttton** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#32]
The chapter based on example when dog Simon tracking in hallway. The hallway is described as one-dimensional array with length 10.

> To keep the problem small, we will assume that there are only 10 positions in a single hallway to consider, which we will number 0 to 9, where 1 is to the right of 0, 2 is to the right of 1, and so on.

And all sections use this data domain. But two sections use different data: **Incorporating Movement Data** and **Adding Noise to the Prediction**.

In the **Incorporating Movement Data** section is used array with length 4 (but it is still talk about the Simon in the hallway).

At the beginning of the **Adding Noise to the Prediction** section is used array with length 8, but later used common data domain - array with length 10.

This is not error! All charts matched with corresponding code in Python and description, but, in my opinion this is some kind of drawback.

**Comment by rlabbe** [comment]
I agree, and tonight's check in fixes this.
