### ISSUE TITLE
chapter 12: Computing the State Estimate formula not rendering on github

### ISSUE THREAD

**Issue by milesvp** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#325]
Just an FYI, in the section "Computing the State Estimate" there is an equation that isn't rendering in either Firefox or Chrome on github. Renders fine in jupyter notebook (firefox) though. No idea what the problem might be, else I'd link to a pull request to fix...

$$ \mu = \frac{1}{N}\sum\limits_{i=1}^N w^ix^i$$

https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/12-Particle-Filters.ipynb

**Comment by rlabbe** [comment]
looks like adding \displaystyle to the equation fixes rendering.
