### ISSUE TITLE
Sensor as Measurement or Control Input

### ISSUE THREAD

**Issue by munich-dev** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#326]
When I have two sensors, let's say a position and a velocity sensor. How do I decide if I put both sensors as measurements into the Kalman Filter or if I put the position sensor as measurement and the velocity sensor as control input? 

Thank you

**Comment by rlabbe** [comment]
I don't really understand your question. Velocity sensors are not controls, they are sensors. Both sensors should be measurement inputs.

**Comment by munich-dev** [comment]
In your example in https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/11-Extended-Kalman-Filters.ipynb you also use the velocity and steering angle as control input. I assume they are also emitted by a sensor? So why are they not fed in to the filter as a measurement but as control input?

**Comment by rlabbe** [comment]
But those are control inputs. In my example you sending a command via the steering wheel and accelerator (or something) to move the robot. You stated that you have a position and velocity sensor - I assumed you meant they are measuring the current position and velocity. That is entirely different from a control input such as the steering wheel on an automobile/bike/robot. Control input means you are using machinery to modify some control surface - wheels, engine, aileron, or what have you.

**Comment by munich-dev** [comment]
Okay, thanks for clarification.
