### ISSUE TITLE
Markdown typos in chapter 02

### ISSUE THREAD

**Issue by IvanVnucec** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#328]
The sentence looks like this: 

`A few words about the [mode](https://en.wikipedia.org/wiki/Mode_(statistics)) of a distribution.`

I think the word "mode" should be linked but it isn't because of the ')' character at the end of link.
User would find the typo easily with CTRL+F.

Another typo is in code:
`belief = np.array([1./3, 1./3, 0, 0, 0, 0, 0, 0, 1/3, 0])` where last fraction 1/3 isn't like the first two with dot: 1./3.

**Comment by rlabbe** [comment]
Thanks.
