### ISSUE TITLE
Ch03 sum of two Gaussians is Gaussian?

### ISSUE THREAD

**Issue by wilcobonestroo** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#332]
In chapter 3 there is a sentence
> A remarkable property of Gaussian distributions is that the sum of two independent Gaussians is another Gaussian

To me, this looks like an error. For example, if they have different means, the sum will be a function with two "bumps". Is this correct, or am I missing something here?

**Comment by rlabbe** [comment]
This is poorly written. The sum of two independent, normally distributed variables is proportional to another gaussian. I thought I had all of these mis-expressions cleaned up, but apparently not.

https://en.wikipedia.org/wiki/Sum_of_normally_distributed_random_variables

**Comment by wilcobonestroo** [comment]
Hmm... My confusion was in the distinction between the distribution (function) and random variable. The sum of the two functions is not a normally distributed function, but the sum of two random variables that are normally distributed is normally distributed. [Wikipedia](https://en.wikipedia.org/wiki/Sum_of_normally_distributed_random_variables) describes it as:
> Let X and Y be independent random variables that are normally distributed (and therefore also jointly so), then their sum is also normally distributed

**Comment by The-Fenix** [comment]
Take me off this shit

Jason Wilson
Certified Pressure Testing LLC, Delaware- DBA Certified Holdings LLC
2019 State Route 821
Building 25
Marietta OH 45750
Cell 517-256-6561
jwilson@<mailto:|jwilson@certifiedholdingsllc.com|>cptllc.net
          www.certifiedpressuretesting.com<http://www.certifiedpressuretesting.com/>


On Apr 30, 2020, at 11:32 PM, Wilco Bonestroo <notifications@github.com> wrote:

﻿

Hmm... My confusion was in the distinction between the distribution (function) and random variable. The sum of the two functions is not a normally distributed function, but the sum of two random variables that are normally distributed is normally distributed. Wikipedia<https://en.wikipedia.org/wiki/Sum_of_normally_distributed_random_variables> describes it as:

Let X and Y be independent random variables that are normally distributed (and therefore also jointly so), then their sum is also normally distributed

**Comment by KumarRishabh** [comment]
In my understanding, the concept that generally confuses people is that of convolution of random variables vs mixture of distributions. To avoid this confusion, extensive treatment of the topic might be required
