### ISSUE TITLE
How can I fuse different types of sensors with UKF?

### ISSUE THREAD

**Issue by lyrem0007a** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#334]
I try to fuse different types of sensors using UKF? E.G. how can I use this libriary to fuse the Doppler velocitiy from radar and landmarks from lidar, which are sampled in different tiemstamp? Should I define separate UKF for such asynchronous multimodal sensor data? Thanks!

**Comment by rlabbe** [comment]
I cover the basics of fusing different sensors in the book. Beyond that the topic warrants an entire book on it's own (and they exist). It's pretty far beyond the scope of the book.

But chapter 8 covers the basics of what you are asking. The section "sensor fusion" covers using multiple sensors, and the section "nonstationary processes" covers uneven timestamps.
