### ISSUE TITLE
Particle Filter resampling

### ISSUE THREAD

**Issue by iliar-rabet** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#336]
Hello there,

Thanks for the great job.
I was trying to use the chapter 12. I think in update step, number of samples is never changed. 

```
def update(particles, weights, z, R, landmarks):
    for i, landmark in enumerate(landmarks):
        dist = np.linalg.norm(particles[:, 0:2] - landmark, axis=1)
        weights *= scipy.stats.norm(dist, R).pdf(z[i])
    weights += 1.e-300      # avoid round-off to zero
    weights /= sum(weights) # normalize
```

So the condition below never holds true:

```        # resample if too few effective particles
        if neff(weights) < N/2:
            indexes = systematic_resample(weights)
            resample_from_index(particles, weights, indexes)
            assert np.allclose(weights, 1/N)
```

Actually, the filter never runs the resampling procedure. Any need to change the code?

**Comment by rlabbe** [comment]
I don't understand your comment - the number (size) of weights is supposed to be constant. neff -s N effective - the number of weights that are meaningfully contributing to the computation. 

I don't recall if the specific SIR filter in the book needs to resample or not, but it looks like it converges pretty rapidly, so probably not. You only resample when the the filter degenerates.

**Comment by iliar-rabet** [comment]
Sorry, my mistake.
Thanks for the explanation.

**Comment by zhchyang2004** [comment]
Hi, 

Do you think it more reasonable to rewrite the weight formuler as follows instead of the current version? They can get same results.

weights *= scipy.stats.norm(z[i], R).pdf(distance)
z[i] is the expected mean and distance is from prior.

Thanks
