### ISSUE TITLE
CH 6 - Error with plot_track() arguments

### ISSUE THREAD

**Issue by carpdiem** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#337]
In Chapter 6, beginning with code cell 31, all calls to plot_track return an error:

"TypeError: plot_track() got an unexpected keyword argument 'dt'"

I verified this on both my local clone of the repo, as well as by launching the binder version from the repo's github homepage link, opening up Chapter 6, and selecting Cell -> Run All.

**Comment by rlabbe** [comment]
Fixed, thanks!
