### ISSUE TITLE
Difference between UKF and KF covariance updates?

### ISSUE THREAD

**Issue by DBTaylor** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#338]
In the reference Kalman filter implementation, the process noise covariance Q is propagated to measurement space:
```python
P = dot(F, P).dot(F.T) + Q

#update
S = dot(H, P).dot(H.T) + R
```

In the reference UKF, it is not:
```python
self.xp, self.Pp = unscented_transform(
   self.sigmas_f, self.Wm, self.Wc, self.Q)
```
```python
# rename for readability
sigmas_f = self.sigmas_f
sigmas_h = self.sigmas_h
# transform sigma points into measurement space
for i in range(self._num_sigmas):
   sigmas_h[i] = self.hx(sigmas_f[i])
# mean and covariance of prediction passed through UT
zp, Pz = unscented_transform(sigmas_h, self.Wm, self.Wc, self.R)
```

It seems to me that in the UKF, sigmas_f should be resampled from P prior to capture Q and pass that information to measurement space:
```python
self.sigmas_f = sigma_points_fn(self.xp, self.Pp)
```

Is there something I'm missing?

**Comment by rlabbe** [comment]
Ah, i see. The FilterPy code had exactly this bug; I fixed it, but apparently not the book's text. Would you agree that the FilterPy implementation is correct?

**Comment by DBTaylor** [comment]
> 
> 
> Would you agree that the FilterPy implementation is correct?
Yes, thanks for the confirmation and quick response!

**Comment by rlabbe** [comment]
Fixed, thanks!
