### ISSUE TITLE
Chapter 1: gain_rate confusion

### ISSUE THREAD

**Issue by JeanLuc001** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#389]
The equation

![image](https://user-images.githubusercontent.com/12352013/130325670-7799d2aa-3b13-433a-9f68-5170e94f22f0.png)

confuses me, because in the previous section it was suggested that the weight gain of 4.4 lbs/day should be weighted by 1/3.
However, wasn't the 4.4 computed like

measurement - previous estimate

which would mean

![image](https://user-images.githubusercontent.com/12352013/130325810-8fd19211-cd8d-426d-b377-c4dd0b785ea1.png)
(or even better with a 2/3 in front of "old gain")
?

Can someone clarify?

Instead of this plot

![image](https://user-images.githubusercontent.com/12352013/130325987-a991b75a-8829-4e7f-be27-4b26b463c645.png)

one would get this one:

![image](https://user-images.githubusercontent.com/12352013/130325992-e56a581d-396f-4216-93e4-824462561b85.png)

**Comment by zjysteven** [comment]
@JeanLuc001 Have you ever figured this out? I have the same confusion. Why exactly `new gain` is computed by averaging `old gain` and `residual / dt`? This makes no sense. The equation in your second figure is correct to me.

**Comment by JeanLuc001** [comment]
Hi, sorry, I had moved on with the material and hadn't thought of this problem.
