### ISSUE TITLE
Asking for the author's permission to translate this material

### ISSUE THREAD

**Issue by wjdghksdl26** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#398]
Hello,

First of all, let me express my gratitude for your decision of writing and distributing this superb material.

I've learned more from this book about state estimation and filtering more than my 4 years of university life combined!

Knowledge and insight that I've gained from this book even helped me get a job as an autonomous driving engineer.

I went so far as to think that it would be nice to fork this repository and translate it for my language(korean) so that more people from my country who are interested but uninformed of this subject can share the privilege of studying with this book.

I would like to start working on it if you kindly give me the permission to do so.

Thank you again for sharing your knowledge, and I'll await your response.

**Comment by deadundead** [comment]
A blessing is a good thing, but I believe [CC_4.0](https://creativecommons.org/licenses/by/4.0/) and MIT licenses, under which this book is published, permit you to do so.

**Comment by wjdghksdl26** [comment]
Yes, it does says so. I should have given more attention about the licenses. Thank you for your information!
