### ISSUE TITLE
book PDF file missing in latest zip

### ISSUE THREAD

**Issue by mariocannistra** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#40]
Hi Roger.
After a long pause on the topic I came back to download the latest version and noticed the book PDF is no longer present in the zip (and in the repository).

edit: I just read in one of the recent commits' comment that you actually removed the PDF.
I'm often offline and was relying on the PDF to continue reading...

I get a good number of errors when trying to build the PDF on my laptop... Would you please consider adding back the PDF to the repo?

Kind regards,
Mario

**Comment by rlabbe** [comment]
HI Mario,

git is not designed to work with binary data, and the repository was
getting huge. I had to pull it out. I'm searching for a home for the PDF;
in the meantime if you want a PDF I can generate one and email it to you.
However, now github will render the notebooks if you just click on it. I
know that requires you to be online, though.

Roger

**Comment by mariocannistra** [comment]
Yes please, send me a copy via email.
Will write you in 10s so that you can reply with attachment.
Thank you,
Mario
