### ISSUE TITLE
Am i right?

### ISSUE THREAD

**Issue by andyyuan78** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#42]
It takes them many minutes to slow down or speed up significantly. So, if I know that the train is at kilometer marker 23km at time t and moving at 60 kph, I can be extremely confident in predicting its position at time t + 1 second. And why is that important? Suppose we can only measure its position with an accuracy of 500 meters. So at t+1 sec the measurement could be anywhere from 22.5 km to 23 km. But the train is moving at 60 kph, which is 16.6 meters/second. So if the next measurement says the position is at 23.4 we know that must be wrong. Even if at time t the engineer slammed on the brakes the train will still be very close to 23.0166 km because a train cannot slow down very much in 1 second. 

I think it should be
"So at t+1 sec the measurement could be anywhere from 22.516 km to 23.484 km. But the train is moving at 60 kph, which is 16.6 meters/second. "
since the statement 'with an accuracy of 500 meters' means both + and - ways.
so the next 'So if the next measurement says the position is at 23.4 we know that must be wrong.  ' also need a fix!

**Comment by rlabbe** [comment]
I see what you mean - I neglected to add in the one second movement. But i don't see where your 23.484 comes from. 23 + 60/3600 + .5 = 23.517

**Comment by andyyuan78** [comment]
23 + 60/3600 + .5 = 23.517  sure, it should be this.
