### ISSUE TITLE
Chapter 3: Sum of two independent normal variables is also normally distributed?

### ISSUE THREAD

**Issue by aprimadi** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#420]
Is this true? I tried adding g1 and g2 in Python code and normalized it and the curve is heavier on the right.

My code:
```python
x = np.arange(-1, 3, 0.01)
g1 = gaussian(x, mean=0.8, var=.1)
g2 = gaussian(x, mean=1.3, var=.2)
plt.plot(x, g1, x, g2)

g = g1 + g2  # I CHANGED THIS LINE
g = g / sum(g)  # normalize
plt.plot(x, g, ls='-.');
```

Excerpt from chapter 3:
A remarkable property of Gaussians is that the sum of two independent independent normal variables (https://en.wikipedia.org/wiki/Sum_of_normally_distributed_random_variables) is also normally distributed!

**Comment by rlabbe** [comment]
Your code sums two gaussian distributions, which is a mixture. The sum of two normally distributed random variables is normal. Different things.

https://en.wikipedia.org/wiki/Sum_of_normally_distributed_random_variables

**Comment by rlabbe** [comment]
Looking at the text in more detail, I see that I jump directly from gaussian distributions to normal random variables with no explanation of what the latter means. I'll clarify that.

**Comment by aprimadi** [comment]
I see thanks for clarifying.
