### ISSUE TITLE
Value for state transition in chapter 6

### ISSUE THREAD

**Issue by mzuehli** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#48]
Hi Roger,
first, it's really great that didactically skilled people like you share their knowledge with dumb people like me in such a nice way. I really learned a lot from your book!

I found some issues I want to address. I don't know if this is the right place to do, but I interpreted from your preface that it is. 
Anyway: I implemented my own Kalman filter and it looked quite ugly, so I took the input parameters that you used in chaper 6 when implementing the first full KF. It still didn't look the same and I found that you used for the state transition matrix
F = 1 1
       0 1
The top right index is supposed to be the *step*, right? So, here you use dt=1 and further down for the calculation of the Q matrix in this example you use dt=0.1.

Is that a bug or am I missing something? I haven't read past chapter 6 yet, but to my feeling this is wrong, or? After I changed in my version the state transition to your version, the KF performed like yours.

Cheers
Marko

**Comment by rlabbe** [comment]
Gah. You are absolutely right. I've fixed it and checked it in. I did it quickly, there may be bus remaining...
