### ISSUE TITLE
Enable Discussions feature

### ISSUE THREAD

**Issue by endolith** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#504]
@rlabbe Can you enable the Discussions feature so we can ask questions about the content of book, etc. without filing Issues?

https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/settings

![image](https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/assets/58611/9c43ae7d-c62a-460c-aa8f-57e3387fcbca)

**Comment by rlabbe** [comment]
No, I have no time to moderate content. Stop abusing the issues and pull requests to have discussions. my inbox is flooded with work I have no time or interest in.
