### ISSUE TITLE
Chapter 2: "Finally," that is not followed by anything

### ISSUE THREAD

**Issue by endolith** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#505]
> Now we can see the results. You can see how the prior shifts the position and reduces certainty, and the posterior stays in the same position and increases certainty as it incorporates the information from the measurement. I've made the measurement perfect with the line z_prob = 1.0; we will explore the effect of imperfect measurements in the next section. **Finally,**
> 
> Another thing to note is how accurate our estimate becomes when we are in front of a door, and how it degrades when in the middle of the hallway. This should make intuitive sense. There are only a few doorways, so when the sensor tells us we are in front of a door this boosts our certainty in our position. A long stretch of no doors reduces our certainty.

**Comment by rlabbe** [comment]
Seriously, knock it off. This is work I did 8-10 years ago, I do not have the bandwidth for the multiple emails I get every day from you, you do not "deserve" my free work and time. I worked extremely hard on this book, gave it away for free, you do not get to demand or ask for anything further, you do not get to approve changes, mark things as duplicates, and so on. I honestly don't really care about typos that aren't confusing. It's a lot of work to regenerate a chapter, check that all the figures are still correct, regenerate the pdf, etc. I understand you are enthusiastic, but my inbox is nothing but notifications from this account, most of you replying to years old threads.
