### ISSUE TITLE
Unfinished sentence in chapter 2

### ISSUE THREAD

**Issue by undefx** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#55]
At the very end of the `Tracking and Control` section of [chapter 2](https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/02-Discrete-Bayes.ipynb), the last sentence appears to be truncated:
> In other words, when we call `predict()` we will pass in the commanded movement that we gave the robot along with a kernel that describes the likelihood of

(Maybe the likelihood of distance/destination?)

**Comment by rlabbe** [comment]
Thanks, I've fixed it.
