### ISSUE TITLE
Online Estimate of R(k)

### ISSUE THREAD

**Issue by lakehanne** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#57]
<script type="text/javascript"
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>

Hi,

Nice work on the book and on providing a python implementation.

I recently came across a paper that discussed estimating the measurement noise covariance matrix in an online fashion as follows:

                     \\(\hat{R(k)} = C_v + H \bar{P}(k) H^T\\) 

where 

                \\(\bar{P}(k) \\) is the posteriori error covariance matrix and \\(C_v\\) , at time \\(k\\), is computed from an average moving window of size \\(m\\), as
                      
                          \\(C_v (k) =1/ m  ∑ v(k − 1)v(k − 1)^T\\)

The thing is when I implement this, I find my estimates are really smooth but it takes a long time to reach convergence.

Wondering if you have any idea why this is so. The paper in question is:

>J. Wang, “Stochastic modeling for real-time kinematic gps/glonass position,” Navigation, vol. 46, pp. 297–305, 2000. 

Looking forward to your reply. 

Thank you!

**Comment by rlabbe** [comment]
I really don't know anything about this technique. I do not have access to the paper, or, to be honest, the inclination to dig it out and read it. I did find this [1], which seems to be by the same author. Several pages are missing, though. More googling turns up a lot of research by different people. 

The idea seems to be to estimate R and Q if you cannot estimate the actual errors.  There isn't enough information in the paper (that I can see, at least) to come to any conclusion. They kind of hand wave away the issue of selecting the window size, for example, pointing out that it depends on the satellite geometry. 

In general though, the KF requires that R,Q, etc are all correct, and that the noise is Gaussian and white. This will not be true for any adaptive process, and it will take a long time to converge, and many times will diverge. I gave examples of this in the MKF chapter. I would suspect that there is a strong interaction between the KF output state and the moving window average - this could cause it to take a long time to make an accurate estimate, and hence be sub-optimal?

Anyway, I am not current (I never have been) in this topic of research. 




[1]https://books.google.com/books?id=wNjnCAAAQBAJ&pg=PA325&lpg=PA325&dq=Stochastic+modeling+for+real-time+kinematic+gps/glonass+position&source=bl&ots=6yrwsjg_Bd&sig=yCTJRNM8nazbRA4uIC3_ypQtXl4&hl=en&sa=X&ved=0CF8Q6AEwCmoVChMIs67V9LfYxwIVySUeCh1LZAw8#v=onepage&q&f=false

**Comment by lakehanne** [comment]
Thanks for the reply. 

In the end, after making v(k)= z(k) - H\hat@{X} and calculating R(k) accordingly, I found that my R(k) was essentilly zero thus  making the  gain almost zero. This made the estimates unreliable, basically rendering the kalman filter useless as the measurements now became the observation.

As you said, there's little light on this subject and this makes the validity of the author's claim a little bit unverifiable.
