### ISSUE TITLE
The formula of Total Probability Theorem

### ISSUE THREAD

**Issue by ruoyu0088** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#59]
I think there is a mistake in The formula of Total Probability Theorem in 02-Discrete-Bayes.ipynb.

`P(X^{t−1}_{i})` should be `P(X^{t−1}_{j})`.

**Comment by rlabbe** [comment]
Thank you, finally got around to fixing and pushing this. PDF not updated yet.
