### ISSUE TITLE
Minor issues in chapters 6, 7, 8

### ISSUE THREAD

**Issue by Qgel** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#65]
While reading I stumbled upon the following minor issues. I didn't want to open a new issue for each of them, so here they are:

* 06-Multivariate-Kalman-Filters
  * [..]So, if K is large then (1−cK) is small, and P will be made smaller than it was. If K is small, then (1−cK) is large, and P will be made larger than it was. [..]
    * *Doesn't P get smaller in both cases, just smaller in the first one?*
* 07-Kalman-Filter-Math
  * [..] division is scalar's analogous operation for matrix inversion [..]
    * *Reciprocal is the analogous operation, it's only somewhat division here because of the subsequent multiplication*
  * integration routines such as scipy.integrate.ode. These routines are robust, but *[end of paragraph]*
* 08-Designing-Kalman-Filters
  * [..] a Kalman filter with R=0.5 as a thin blue line, and a Kalman filter with R=10 as a thick red line [..]
    * *On binder at least R=0.5 is a thin green line, and R=10 is a thick blue line*
  * **Tracking Noisy Data**
author's note: not sure if I want to cover this. If I do, not sure I want to cover this here.
      * *Ok, not really a bug. I just hope you do because I would really love that chapter :)*

**Comment by rlabbe** [comment]
Sorry it took so long, but I have fixed all of these issues.

I do not believe I will be writing the Tracking Noisy Data in this book. I do plan to tackle it at some point in either a separate notebook, or a book more specifically aimed towards tracking; the topic gets quite involved.
