### ISSUE TITLE
color_cycle warning with matplotlib 1.5

### ISSUE THREAD

**Issue by chadkennedyonline** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#68]
When executing 

    #format the book
    %matplotlib inline
    %load_ext autoreload
    %autoreload 2  
    from __future__ import division, print_function
    import sys
    sys.path.insert(0,'./code')
    from book_format import load_style
    load_style()

from any page, I get the following warning:

    D:\Chad\Documents\WinPython-64bit-3.4.3.6\python-3.4.3.amd64\lib\site-packages\matplotlib\__init__.py:876: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
      warnings.warn(self.msg_depr % (key, alt_key))

This Python distro is using Matplotlib 1.5.0rc3.  I have confirmed that changing the axes.color_cycle line in 538.json to 

      "axes.prop_cycle": "cycler('color', ['#6d904f','#013afe', '#202020','#fc4f30','#e5ae38','#A60628','#30a2da','#008080','#7A68A6','#CF4457','#188487','#E24A33'])",

fixes the warning. But I am unsure how to make the json file conditional based on Matplotlib version, so as to be backwards compatible with older distributions.

**Comment by rlabbe** [comment]
I just pushed a version that detects the matplotlib version and uses the appropriate settings. Let me know if it doesn't work for you.

**Comment by dnstanciu** [comment]
Hi, I downloaded a fresh copy and I get this error when running the snippet posted by @chadkennedyonline :
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-25-a550bbe40f47> in <module>()
      7 sys.path.insert(0,'./code')
      8 from book_format import load_style
----> 9 load_style()

/home/dragos/Projects/Kalman-and-Bayesian-Filters-in-Python/code/book_format.pyc in load_style(directory, name)
    130         s.pop("axes.color_cycle", None)
    131 
--> 132     plt.rcParams.update(s)
    133     reset_axis ()
    134     np.set_printoptions(suppress=True)

ValueError: dictionary update sequence element #0 has length 1; 2 is required
```
When I *print (s)*, I get *1*. I'm guessing that rcParams expects a (key,value) pair. Could you please fix this? Not being able to run the first cell messes up the formatting... Thank you!

**Comment by rlabbe** [comment]
@dnstanciu can you tell me your environment - Python version, IPython version, OS, python package if you are using one(anaconda or whatever)? I cannot duplicate this here, so I'm hoping this will help me diagnose the problem.

**Comment by dnstanciu** [comment]
When I got the error, my setup consisted of:
Python 2.7.6;  IPython 4.0.0; Ubuntu 14.04; not using anaconda; matplotlib 1.3.1; running ```ipython notebook``` from the base directory. 

After updating all my PIP packages, I got a new error:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-34-a550bbe40f47> in <module>()
      7 sys.path.insert(0,'./code')
      8 from book_format import load_style
----> 9 load_style()

/home/dragos/Projects/testkalmanbook/Kalman-and-Bayesian-Filters-in-Python/code/book_format.py in load_style(directory, name)
    127 
    128     if version[0] > 1 or (version[0] == 1 and version[1] >= 5):
--> 129         s["axes.prop_cycle"] = "cycler('color', ['#6d904f','#013afe', '#202020','#fc4f30','#e5ae38','#A60628','#30a2da','#008080','#7A68A6','#CF4457','#188487','#E24A33'])"
    130         s.pop("axes.color_cycle", None)
    131 

TypeError: 'unicode' object does not support item assignment
```
I realized that the ```s``` dictionary was being overwritten in line 127:
```python
version = [int(s) for s in matplotlib.__version__.split('.')]
```
That explains why I was getting 1 instead of the JSON settings...
So I changed ```s``` to ```version_no``` in line 126 and it all works ok now! I've submitted a pull request, if you'd like to accept my small contribution: #70 . Cheers!

**Comment by rlabbe** [comment]
I've accepted the pull request (thanks!) and haven't heard of any more problems, so I'm closing it. Please reopen if you are still having problems.
