### ISSUE TITLE
Cannot see equations in Ch. 10

### ISSUE THREAD

**Issue by lambdasigmaetapi** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#69]
It might be an operating system/browser problem, but I cannot see the equations properly for chapter 10 (I haven't tried other chapters). Attached is a screenshot of what I see using Firefox Mozilla v. 42.0 on Ubuntu 12.04 LTS.
![screenshot](https://cloud.githubusercontent.com/assets/11504535/11122885/70258094-895d-11e5-8648-0ad26ff12703.png)

**Comment by rlabbe** [comment]
I can not duplicate this on my machines(windows and xubuntu), however, I do install MathJax locally (MathJax renders the math equations).

You can view the pages remotely via the following links. Can you see the equations using these links?

https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/10-Unscented-Kalman-Filter.ipynb

http://mybinder.org/repo/rlabbe/Kalman-and-Bayesian-Filters-in-Python

http://nbviewer.ipython.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/10-Unscented-Kalman-Filter.ipynb

I'll be honest, I don't know what I'll conclude depending on whether you say 'yes' or 'no' to these links. 

Are you still having these problems? By default MathJax is served remotely - if MathJax was down when you opened the file you could end up with no math rendered.

I'll try building a new Ubuntu virtual machine to see if I can duplicate your problem. It would help to know the version/installation/distribution of Python, IPython that you are using.

**Comment by lambdasigmaetapi** [comment]
Thank you for your e-mail, much appreciated! The second and third links 
worked for me. (The first is the one that gave me problems in the first 
place.)

I'll take the opportunity to thank you for making your work so easily 
available. Although I wrote my own filter, the system is rather complex 
and I'm an absolute beginner when it comes to Kalman filters, so being 
able to compare with yours is giving me more confidence than I would 
have had otherwise.

Regards,


Lara

**Comment by rlabbe** [comment]
I just want to follow up on this. I haven't heard from anyone else that they cannot read the equations via the github interface. If anyone is still having problems please let me know. I don't know what I can do about it, but if it is failing for a large number of people either I have a problem or we need to escalate this to the correct project (probably nbviewer?) so they know about it.

**Comment by rlabbe** [comment]
I haven't received an update on this, nor reports from others, so I am going to assume this was a one time glitch. Please re-open or write a new issue if the problem persists.
