### ISSUE TITLE
Duplicated words in chapter 1

### ISSUE THREAD

**Issue by jminer** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#72]
Here's a couple typos I noticed while reading chapter 1:

- "Now, let's assume we we gained weight."

  "we" is duplicated.

- "For example, for the 100 kg weight weight our estimate might be 99.327 kg due to sensor errors."

  "weight" is duplicated.

**Comment by rlabbe** [comment]
I just pushed fixes for these. Thanks!
