### ISSUE TITLE
Chapter 2.13 Total Probability Theorem

### ISSUE THREAD

**Issue by sudiptakarmakar** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#73]
The formula for total probability theorem is wrong here. Probability of being at position *i* at time *t*,
P(x<sub>i</sub><sup>t</sup>) is given by the sum of probabilities of being at position *j* at time *t-1* multiplied by probability of moving from position *j* to *i* at time *t*. Therefore, it will be,
P(x<sub>i</sub><sup>t</sup>) = for all *j*, sum of ( P(x<sub>j</sub><sup>t-1</sup>) * P(x<sub>i</sub>|x<sub>j</sub>) )

**Comment by rlabbe** [comment]
Thank you. I just pushed the fix. PDF has not been updated yet.
