### ISSUE TITLE
Error using binder. Cant import filterpy 

### ISSUE THREAD

**Issue by stoiver** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#74]
Hi,

Just tried to use binder to read your book. (Nice work, well done). 

But when trying to run some code, such as the first cell in 01-g-h-filter.ipynb I get the following error which implies that filerpy has not been installed, though I note that filerpy is listed in requirements.txt. 

Here is the error message I get. 

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-26d5dd208d25> in <module>()
      2 get_ipython().magic('matplotlib inline')
      3 from __future__ import division, print_function
----> 4 from book_format import load_style
      5 load_style()

/home/main/notebooks/book_format.py in <module>()
     59 # called when this module is imported at the top of each book
     60 # chapter so the reader can see that they need to update FilterPy.
---> 61 test_filterpy_version()
     62 
     63 

/home/main/notebooks/book_format.py in test_filterpy_version()
     39 
     40 def test_filterpy_version():
---> 41     import filterpy
     42     min_version = [0,0,28]
     43     v = filterpy.__version__

ImportError: No module named 'filterpy'

**Comment by rlabbe** [comment]
So sorry, looks like I neglected to include the requirements.txt file. I just rebuilt the image and it looks like it is working now.

**Comment by stoiver** [comment]
Yes it is now working for me too. Thanks
