### ISSUE TITLE
Is the Update equation in the Univariate kalman filter class correct?

### ISSUE THREAD

**Issue by oxinabox** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#8]
In http://nbviewer.ipython.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/05_Kalman_Filters/Kalman_Filters.ipynb

Hi,
I am rather enjoying going though your book. (Currently working though and translating bits of it into julia for my understanding of both Julia and Kalman filters.)
I appreciate it is a work in progress.

at In[89]:
```
    def update(self, z):
        self.x = (self.P * z + self.x * self.R) / (self.P + self.R)
        self.P = 1. / (1./self.P + 1./self.R)
```
My instincts are telling me that this should be:

```
    def update(self, z):
        self.x = (self.R * z + self.x * self.P) / (self.P + self.R)
        self.P = 1. / (1./self.P + 1./self.R)
```

Because `P` is the variance (uncertainty) of the state,
and `R` is the variance of the measurement.

I'm not to certain though.
If I am wrong, perhaps the section could be written to make it more clear why this should be the case.

**Comment by rlabbe** [comment]
HI Lyndon, 

Surprisingly, the equation is correct. Forget about P and R, and what they mean for a moment, and remember the equation for multiplying two Gaussians:

(mu1, var1) * (mu2, var2) = (mu1*var2 + mu2*var1) / (1/var1 + 1/var2)

Okay, so you can go do the algebra and prove that, but *why* does this make sense? Back to P and R. These numbers are larger when our uncertainty is larger. When we update we are trying to balance between the prediction (self.x) and the measurement (z). If we are extremely unsure about the prediction (say we are tracking a hummingbird that darts around), then we want to mostly take the measurement. 

For example, say P=9 (standard deviation = 3meters), and R=1 (standard deviation = 1 meter), which means the error in the prediction is worse than the error in the measurement. The updated x =  (9z + 1x) / (9+1). We take 9/10s of the measurement z, and 1/10 of the prediction (here P=9, R=1). The last few paragraphs above the "Implementing the Update Step" go through this explanation, but I see in fairly abstract terms. I'll revise it to be a bit more concrete.

Did that make sense?

**Comment by oxinabox** [comment]
That does make sense.

I misread the multiplying Gaussians equation.
I kept scrolling back to it. (It is referred to at the top of the page, then until the class is implemented the `multiply` function is used.)

It might be nice, if it was repeated prior to the class being defined.

Thanks alot.
