### ISSUE TITLE
Unscented Kalman Filter: using of `lambda` and `kappa` is unclear

### ISSUE THREAD

**Issue by Gluttton** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#80]
I have a question about Chapter 10 "Unscented Kalman Filter".

In paragraph "Implementation of the UKF: Sigma Points" in the sigma point equation under square root is placed `lambda`. Later (in the text) instead of `lambda` used `kappa`. Later at the source code snippet:

   `U = scipy.linalg.cholesky((n+kappa)*P)`

used `kappa` too.

In paragraph "Choosing the Sigma Parameters" used `lambda` again.

But in the description of the filter by [link](https://filterpy.readthedocs.org/en/latest/kalman/UnscentedKalmanFilter.html) used `kappa`.

So my question is: what is the correct equation for the sigma points? Is this error or I have missed some thing?

**Comment by rlabbe** [comment]
I'm at work, so I'll have to look later. There are multiple algorithms for
finding the Sigma points. Van der Merwe uses lambda, Julier's technique
uses kappa. It's possible the text or code messed this up, or maybe the
different sections are using algorithms. I'll look, and clarify or fix as
warranted. In the meantime, I hope this helps.

**Comment by Gluttton** [comment]
> I'm at work, so I'll have to look later.

It's not a problem.

> Van der Merwe uses lambda, Julier's technique uses kappa.
> I hope this helps.

Yes, this is useful information for me.

But anyway I leave this issue opened, until you do not have free time to consider this issue more closely.

Thanks for quick reply!

**Comment by rlabbe** [comment]
You are right, the text was wrong, and I've made the fixes and pushed them. Thanks so much!
