### ISSUE TITLE
Unscented Kalman Filter:  constraint for weights of covariances computed by Van der Merwe's algorithm

### ISSUE THREAD

**Issue by Gluttton** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#81]
I have a question about Chapter 10 "Unscented Kalman Filter".

In paragraph "Implementation of the UKF: Choosing Sigma Points" specified that sum of weights of means and covariances must be equal one.

Later In paragraph "Implementation of the UKF: Van der Merwe's Scaled Sigma Point Algorithm: Weight Computation" specified the equation for weights computation.

When I try to compute weights using the algorithm with suggested parameters (for two dimensions):
 - `alpha` = 0 ... 1;
 - `beta` = 2;
 - `kappa` = 1.

I will get residual with constraint for weights of covariances. For different values of `alpha` the sum of weights lies between `3` and `4`.

![wcsum](https://cloud.githubusercontent.com/assets/619261/13381941/41590510-de71-11e5-8912-45fd880d2ae9.png)

Changing number of dimensions or `kappa` has no effect. I have found out that to reduce the residual `beta` must be equal `-2`.

So my questions:
 - do you have the similar results of computations (sum of weights of covariances)?
 - if yes, should I always respect the constraints?
 - If yes, should I normalize weights myself?
 - <s>If no, maybe instead adding `beta` should be used subtraction?</s>

**Comment by rlabbe** [comment]
That's a good observation. I was wrong to state that the sums must equal one. The weights for the means are W_0 = L/(N+L) and W_i = 1/(2(N+L). There are 2N W_i , so the sum is (L+N)/(L+N) = 1.

But the 0-th weight for the covariance is W_0 = L(N+L) + (1 - a^2 + b) and the rest are the same as for the mean, so there is no way for the sum to be one unless you choose b-a^2 = -1.

The paper to read on this is Julier's The Scaled Unscented Transformation. The problem he sets out to solve is to minimize the effect higher order moments (skew, kurtosies, etc) have, as the sigma points just estimate the first two moments (mean and variance). The 'extra' data imparted by the 1-alpha^2+beta term  adds some weight to the center point to account for the effect of the higher order moments. You form a Taylor series for the covariance and then compute the error terms for each moment.  If you work through the math, beta=2 minimizes this term if x is gaussian. It's all a bit too much math for my book. Maybe I should redouble my efforts and try to simplify it, I know I didn't do a good job of describing how to choose values for these parameters.. 

The paper is here:

https://www.cs.unc.edu/~welch/kalman/media/pdf/ACC02-IEEE1357.PDF

**Comment by Gluttton** [comment]
Thanks for your detailed answer!

> I was wrong to state that the sums must equal one.

This is answer what I'm looking for.

>The problem he sets out to solve is to minimize the effect higher order moments
> beta=2 minimizes this term if x is gaussian

It looks like, this is my case.    

> Maybe I should redouble my efforts and try to simplify it, I know I didn't do a good job of describing how to choose values for these parameters.. 

I haven't thought so. There are a lot of readers and each one has different questions related with his problem, so you never guess what chapter you should describe better. You have given clue and in my opinion this is good enough.

Thanks again!

**Comment by KarasCvs** [comment]
> That's a good observation. I was wrong to state that the sums must equal one. The weights for the means are W_0 = L/(N+L) and W_i = 1/(2(N+L). There are 2N W_i , so the sum is (L+N)/(L+N) = 1.
> 
> But the 0-th weight for the covariance is W_0 = L(N+L) + (1 - a^2 + b) and the rest are the same as for the mean, so there is no way for the sum to be one unless you choose b-a^2 = -1.
> 
> The paper to read on this is Julier's The Scaled Unscented Transformation. The problem he sets out to solve is to minimize the effect higher order moments (skew, kurtosies, etc) have, as the sigma points just estimate the first two moments (mean and variance). The 'extra' data imparted by the 1-alpha^2+beta term adds some weight to the center point to account for the effect of the higher order moments. You form a Taylor series for the covariance and then compute the error terms for each moment. If you work through the math, beta=2 minimizes this term if x is gaussian. It's all a bit too much math for my book. Maybe I should redouble my efforts and try to simplify it, I know I didn't do a good job of describing how to choose values for these parameters..
> 
> Julier's paper is here:
> 
> https://www.cs.unc.edu/~welch/kalman/media/pdf/ACC02-IEEE1357.PDF

I'm sorry for the sudden reply, I'm facing a serious problem and have no idea how to fix it.
I'm trying to estimate a dynamic system with UKF which like the following.

https://ibb.co/8xYXN7w

This system is from example 13.3 of <OPTIMAL STATE ESTIMATION> written by Dan Simon.

I tried a lot of methods to calculate the weight of sigma points, but the only workable one is to set lambda as a constant(I tried 1~10 and even 100 and 1000, they all works) and set both the weight of covariance and mean w_0 = lambda/(lambda+n), w_i=1/(2*(lambda+n)).
All other methods will cause the covariance matrix P negative definite. Is this caused by the calculating error of python? Or it means that for this system, I can only use a "traditional" method to calculate sigma points?
