### ISSUE TITLE
Test book in multiple Python versions

### ISSUE THREAD

**Issue by rlabbe** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#83]
A reader stated that they had difficulty using Python 2, and had to switch to 3. It is time to test 2.7, 3.3, 3.4, 3.5.

**Comment by rsvp** [comment]
@rlabbe hi Roger, as baseline, which Python version are you running locally?

In reading issue #82, I suspect that the problem in python2 can be traced to absolute_import, and some python2/3 compatible syntax could be used for clarification, for example:

`from code import book_plots`

`from code.book_plots import interactive_plot`

The notebooks render fine statically, but when the user executes some code snippets the "recommended" cross-version syntax may be helpful.

**Comment by rlabbe** [comment]
I've been staying on the bleeding edge of Python 3 and IPython releases. I use conda, and as soon as there is a release in the channel I upgrade. Which has it's pluses and minuses, of course. I love the work that Jupyter is doing, of course, but they are moving fast and breaking things right now, so I have elected to try to keep up rather than get left behind. 

Backporting to 2.7 is not normally a problem; I should get it done this weekend. I need to investigate if there is a good testing framework for the Notebooks; it is quite tedious to have to create N environments, open every notebook by hand, and run it. That's a lot of work if you want to (and I do) support multiple version of Python and IPython (and now Jupyter).

**Comment by rsvp** [comment]
@rlabbe Your work is very much appreciated.

Re: "open every notebook by hand": BTW there is the ***runipy** package which will batch run notebooks, which is sort of integration testing. As for testing, conda environments seem more robust than using virtenv ones.

**Comment by rlabbe** [comment]
I've tried runipy. It doesn't currently work with the `%matplotlib notebook` magic.I've submitted a feature request and the author has agreed to add it.

**Comment by rsvp** [comment]
@rlabbe That's terrific! I have been using `%matplotlib inline` in public branches and tests directories since `%matplotlib notebook` chokes some browsers under circumstances which seems  user-idiosyncratic. Extending testing to different browser environments would be a hassle -- so wishing that the *notebook* option would self-test then fallback to *inline* whenever necessary.

Please kindly let us know when your feature is added to **runipy**.
