### ISSUE TITLE
 Unscented Kalman Filter: suggestions to improve problem domain description

### ISSUE THREAD

**Issue by Gluttton** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#85]
I have a few suggestion to improve problem domain description of para "Tracking an Airplane" of "Unscented Kalman Filter" chapter. First of all, this improvements not related with the main topic of your book, so them is not important. Also improving of problem domain description can pollute the main idea. So you should decide accept some of them or reject, but anyway I'd like notice about them.

You wrote:
> We will track one dimension on the ground and the altitude of the aircraft.

But later you wrote:
> By timing how long it takes for the reflected signal to return it can compute the slant distance and bearing to the target.

We can’t compute bearing to the target by timing.

> The angular determination of the target is determined by the directivity of the antenna.
[link](http://www.radartutorial.eu/01.basics/Direction-determination.en.html)

If we measure altitude then more appropriate use the "elevation angle" instead of "bearing".

> The elevation angle is the angle between the horizontal plane and the line of sight, measured in the vertical plane.
[link](http://www.radartutorial.eu/01.basics/Measurement%20of%20the%20elevation%20angle.en.html)

Also such radars called height finders.
> A height finder is a ground based aircraft altitude measuring device.
[link](https://en.wikipedia.org/wiki/Height_finder)

You wrote:

> Radars also provide velocity measurements via the Doppler effect, but we will be ignoring this complication for the moment.

Velocity of flying object can be calculated using radar measurement, but strictly speaking radar can't measure velocity, instead radar can measure radial velocity.

> Only the radial component of the speed is relevant. When the reflector is moving at right angle to the radar beam, it has no relative velocity. Vehicles and weather moving parallel to the radar beam produce the maximum Doppler frequency shift.
[link](https://en.wikipedia.org/wiki/Radar#Doppler_effect)

You wrote:
> We compute the (x,y) position of the aircraft from the slant distance and bearing as illustrated by this diagram:

This is very subjective judgement but in my opinion using (x,z) instead of (x,y) will be better (by the way, in code snippet 15 you use `dz` as delta of altitude).

In your chart `ekf_internal.show_radar_chart`:
You used theta as elevation angle usually theta used for bearing but epsilon used for elevation angle.

You wrote:
> A typical radar might update only once every 12 seconds so we will use that for our epoch period.

As far as I'm concerned this is true if we talk about surveillance radars, but for height finder this time usually smaller (about 3 seconds).

I hope that this will be helpful for You!

**Comment by rlabbe** [comment]
I should probably change this example; I am not a radar person and probably shouldn't be writing about it.

**Comment by rlabbe** [comment]
I've just checked in changes to fix this. Thanks.
