### ISSUE TITLE
Non-linear filter example is linear

### ISSUE THREAD

**Issue by ryanpdwyer** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#87]
The Non-linear filter notebook opens with the example,

> There can be nonlinearity in the process model. Suppose we wanted to track the motion of a weight on a spring, such as an automobile's suspension. The equation for the motion with $m$ being the mass, $k$ the spring constant, and $c$ the damping force is 
>
>$m\frac{d^2x}{dt^2} + c\frac{dx}{dt} +kx = 0$
>
>There is no linear solution for $x(t)$ for this second order differential equation, and therefore we cannot design a Kalman filter using the theory that we have learned.

which is a linear system described by the state variables x, $\frac{dx}{dt}$.

**Comment by rlabbe** [comment]
If you solve for the fundamental matrix using Laplace transform you end up with

e^(aT)(-a sin bT + b cos bT)/b 

in the [0,0] position of the matrix, with similar terms in the rest of the rows and columns. The KF can not track this behavior reliably in the presence of process noise. Paul Zarchan's book covers this example in some depth p 205-218 in the third edition. I admittedly did not work through the example in my book.

**Comment by ryanpdwyer** [comment]
I read the section from Zarchan's book you referenced. In the example, the errors are caused by discretizing and assuming a forcing term (not present in your equation) is constant between sampling points. The solution presented in the book is to artificially add noise to the Kalman filter, still using a linear Kalman filter for the linear system.

The line,

> There is no linear solution for $x(t)$ for this second order differential equation, and therefore we cannot design a Kalman filter using the theory that we have learned.

is incorrect as currently written. A regular Kalman filter will work perfectly fine for this system, as the example you reference indicates. There may be reasons to use extended / scented Kalman filter on this or a similar system: perhaps some of the system parameters are not perfectly known, or drift with time, or the drag is better modeled as proportional to velocity squared. Any of these modifications / clarifications could provide better motivation for non-linear filtering.

**Comment by rlabbe** [comment]
Thank you for taking the time to write this. I have replaced this example with a nonlinear problem of a falling object in an atmosphere and checked in the changes.
