### ISSUE TITLE
Possible typo ?

### ISSUE THREAD

**Issue by rjpereira** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#88]
In 06-Multivariate-Kalman-Filters.ipynb you write

> Your job as a designer will be to design the state (x,P), the process (x,P), the measurement (z,R), and the unexplained measurement function H. If the system has control inputs, such as a robot, you will also design B and u.

I think you mean .... the process(F,Q) ....  ?

**Comment by rlabbe** [comment]
Yes, good catch. Thank you. I've fixed it and pushed an update.
