### ISSUE TITLE
You may want to clarify this:

### ISSUE THREAD

**Issue by rjpereira** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#89]
In /06-Multivariate-Kalman-Filters.ipynb you are explaining ndarray and state

> However, NumPy recognizes 1D arrays as vectors, so I can simplify this line to use a 1D array.
    x = np.array([10.0, 4.5])
    x

Since before you have explained how X should be a nx1 matrix having said that

    x = np.array([[10.0, 4.5]]).T

I assume you want to say that you could write x = np.array([10.0, 4.5]).T (i.e. with transpose) to mean the same thing as double brackets, transpose.

**Comment by rlabbe** [comment]
Actually, transpose on a single dimension array has no effect - the shape is unaffected. np.dot will handle the fact that x has a single dimension correctly, so no change is needed. I'll think about how to clarify this.

**Comment by rlabbe** [comment]
I've added an example.
