### ISSUE TITLE
Various punctuation and typos

### ISSUE THREAD

**Issue by jminer** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#93]
Chapter 2

- http://nbviewer.jupyter.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/02-Discrete-Bayes.ipynb#Terminology
In the 4th paragraph of the section, "how dog's behave" should be "how dogs behave".
- http://nbviewer.jupyter.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/02-Discrete-Bayes.ipynb#The-Discrete-Bayes-Algorithm
In the update step 3, "Determine whether whether the measurement" should be "Determine whether the measurement"

Chapter 3

- http://nbviewer.jupyter.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/03-Gaussians.ipynb#Nomenclature
In 2nd to last paragraph of the section, "forcing us to use computationally expensive alternative" should be "forcing us to use a computationally expensive alternative" or "forcing us to use computationally expensive alternatives" or something.

Chapter 4

- http://nbviewer.jupyter.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/04-One-Dimensional-Kalman-Filters.ipynb#Understanding-Gaussian-Multiplication
After two code samples, "because I know have two readings" should be "because I now have two readings".
- http://nbviewer.jupyter.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/04-One-Dimensional-Kalman-Filters.ipynb#Exercise:-Modify-Variance-Values
The second sentence in the section, "Which has a larger effect on the variance convergence?." has a period after a question mark when it shouldn't.
- http://nbviewer.jupyter.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/04-One-Dimensional-Kalman-Filters.ipynb#KF-Animation
In the last paragraph of the section, "how much it changed for the firs noisy measurement" should be "how much it changed for the first noisy measurement".
- http://nbviewer.jupyter.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/04-One-Dimensional-Kalman-Filters.ipynb#Introduction-to-Designing-a-Filter
In the first paragraph, "lets get a feel for it" should be "let's get a feel for it".
- http://nbviewer.jupyter.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/04-One-Dimensional-Kalman-Filters.ipynb#Example:-Extreme-Amounts-of-Noise
In the first paragraph, "standard deviation of 300 meters?." has a period after a question mark when it shouldn't.

Chapter 5

- http://nbviewer.jupyter.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/05-Multivariate-Gaussians.ipynb#Multivariate-Normal-Distribution-Equation
After the first code sample, "probability density of for any value" has "of" and "for".
- http://nbviewer.jupyter.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/05-Multivariate-Gaussians.ipynb#Multivariate-Normal-Distribution-Equation
In the next paragraph, "If we think of this as a the Gaussian" has "a" and "the".

**Comment by rlabbe** [comment]
Thank you. I just pushed all of these changes.
