### ISSUE TITLE
IMM algorithm incorrect index

### ISSUE THREAD

**Issue by rhristov** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#94]
I believe one of the formulas for the Mixing probabilities in chapter 14 has a wrong index:

`    P0[j] = sum_over_i(w[i, j] * (P[i] + np.outer(x[i] - x0[i])))`

The last term should be x0[j]. This is the case in the filterpy IMM implementation: https://github.com/rlabbe/filterpy/blob/master/filterpy/kalman/IMM.py. 

Also in IMM Estimate section, I think the intention is to use x hat and P hat when computing x and P, but I don't know whether this notation is better.

**Comment by rlabbe** [comment]
Thanks, I have fixed both and pushed the corrections.
