### ISSUE TITLE
Wrong notaion for non-linear process and measurement model in EKF Notebook

### ISSUE THREAD

**Issue by sauravrt** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#95]
The 'Linearizing the Kalman Filter" section begins by stating the process and measurement models for both linear and non-linear case. The process model equations use x_bar on the LHS. If my understanding is correct, it should be x_dot for both linear and non-linear cases?

**Comment by rlabbe** [comment]
The result of the process model is the prior, which is denoted by x_bar. x_dot is the derivative of x, and so would not be correct.

**Comment by sauravrt** [comment]
I agree that the result of the process model is the prior, denoted by x_bar. But the issue that I'm concern with is that, the first equation in the section [Linearizing the Kalman Filter](http://nbviewer.jupyter.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/07-Kalman-Filter-Math.ipynb#Modeling-a-Dynamic-System) is mentioned as the process model x_bar = Ax + Bu + w_z.
Shouldn't it be x_bar = Fx + Bu with F as the state transition matrix? Matrix A has been used as system dynamics matrix in [previous chapters](http://nbviewer.jupyter.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/07-Kalman-Filter-Math.ipynb). 

Just before you begin the Example: Tracking a Airplane, you have a comparative table showing linear KF and EKF equations. Here you have the process model equation in the correct form.

**Comment by rlabbe** [comment]
Sorry, just getting to this. I skipped a few steps in my explanation, to be sure. I leaped from linear to nonlinear without discussing the transition. I'll clarify this section. Thanks.

**Comment by rlabbe** [comment]
Okay, this is fixed and checked in.

**Comment by sauravrt** [comment]
Appreciate it. Thanks!
