### ISSUE TITLE
Slider do not display in interactive display

### ISSUE THREAD

**Issue by luyuechao** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#96]
Slider do not display in interactive display in both python2 and 3 kernel. I cannot change the variables to change the display.
The slider is OK when run from binder. 
I searched and tired a lot and cannot find which package I need. I'm using mac osx 10.11 and chrome 50, and installed every package required.
Thank you for your time!

**Comment by rlabbe** [comment]
I really don't know how to fix this, and have not heard this problem from anyone else. I will assume this is a problem with a local installation and close.

**Comment by markspeters** [comment]
For me I already had ipywidgets installed and they just needed to be enabled in Jupyter: 

```
$ jupyter nbextension enable --py widgetsnbextension
```

per https://ipywidgets.readthedocs.io/en/latest/user_install.html

I assume that marking the notebook as "Trusted" so it can run Javascript is also required.
